
import type { ChoiceItem, Colleague, CustomColleagueOption } from '../types';

export const CAREER_INTRO_DATA = {
    title: "YOUR CAREER",
    imageSrc: "/images/ZzY31WMJ-main2.jpg",
    description: `The graduation of a mage is a pretty big ceremony, with people coming in from all over the Dominion, or even the world, just to witness the event. You had to complete one last 'test' before you were officially graduated – a formality, of course. It was more of a choreographed show than a proper exam, giving you the opportunity to show off everything you've learned before an adoring, cheering crowd. Maybe you awed your spectators by punching a hole clear through a massive boulder, or by creating a gorgeous show of light and water, or by demonstrating the sheer power of one of your magnificent inventions? Whatever the case, I'm sure it will be a big confidence boost as you enter the next exciting stage of your life.

When you were a child, you had a family there to make all of your decisions for you; when you were in school, your life was heavily regimented; but now you're all grown up, and all of your decisions are your own from now on. For many mages, this is terrifying... and for others, it's invigorating! With no one looking over you, it's finally time for you to go out there and forge your own destiny. The entire world is your oyster! Of course, this section is probably going to be a little more freeform than the previous, since you could theoretically do just about anything you want. Whatever you want to try, I wish you good luck! With talent like yours, I'm sure nothing could stop you from achieving your goals.`
};

export const ALLMILLOR_INTRO_DATA = {
    title: "THE ALLMILLOR",
    imageSrc: "/images/CKVdHzks-main4.png",
    description: `Mages are, while not required, {i}strongly{/i} encouraged to dedicate at least some of their free time to fighting Allmillor whenever they pop up in their Dominion. That is, after all, what mages are created for — to counter the number of Allmillor rising up from the Othersky at a worrying, gradually increasing rate. As a basic explanation, the Allmillor are essentially computer viruses that leak in through cracks in the security of our reality, transmitted here from the Greater Net. Destruction may not necessarily be their goal, but it's an inevitable product of their chaotic behavior. Some people think we will be able to one day staunch this threat once and for all, while others believe that our universe will inevitably be overrun, hence all the efforts to emigrate to a better, more secure dimension. Anyway, that's all irrelevant to you. All you need to do is choose {w}up to three{/w} Allmillor to specialize in fighting. Don't worry, the casualty rate is very low!`
};

export const ALLMILLOR_CHOICES_DATA: ChoiceItem[] = [
    {
        id: 'grimsayer',
        title: 'GRIMSAYER',
        cost: 'Grants +5 FP',
        description: "These things show up a few times a century per Dominion, and it's always a big event when they do. By far the most powerful beasts on this list, and they're definitely not subtle about it; these skyscraper-sized creatures will immediately dedicate their short, brutish lives to sowing as much chaos as possible. They're way too much for most mages to possibly solo, but don't worry, you'll never be dealing with them alone. Every time one appears, pretty much every mage within miles is going to show up to put together an organized counterattack. At that point, these beasts never last long, though watching them get taken down is always very exciting!",
        imageSrc: '/images/chhS2KDv-a1.jpg',
    },
    {
        id: 'nethe',
        title: 'NETHE',
        cost: 'Grants +5 FP',
        description: "The things that go bump in the night. These are the most famous of the Allmillor, viruses poured in from the Greater Net, causing chaos and picking off hapless mundanes on the outskirts of society. They are perhaps the weakest of the creatures on this list, as well as the ones most dominated by raw animal instinct. However, they are the most numerous by far, so expect to spend a lot of your time playing pest control, tracking them down from the details of vague sightings. Don't expect them to put up much of a fight, but that doesn't mean you should underestimate them — on occasion, you'll meet an S-class Nethe that will be significantly stronger than the others.",
        imageSrc: '/images/tPwHJtyg-a2.jpg',
    },
    {
        id: 'sinvains',
        title: 'SINVAINS',
        cost: 'Grants +5 FP',
        description: "Usually the products of horrid Sinthru rituals, these beings are former mages who have been... {i}corrupted{/i}. Their minds have been irreparably broken to the point where they barely have any similarities with the rest of mankind, psychologically. Beasts of utter sadism, their only goal is to sow as much human suffering across the land as they possibly can. They are extremely rare, released every century or so, usually as a distraction from some other Sinthru scheme. Not only do they have a wide variety of powers, but worst of all, they're {i}smart{/i} — the smartest beast on this list, happy to bide their time building their forces or even pretending to still be a normal mage.",
        imageSrc: '/images/jPQfRSLt-a3.jpg',
    },
    {
        id: 'yokai',
        title: 'YOKAI',
        cost: 'Grants +5 FP',
        description: "Jipangu is so proliferated with bizarre old curses and distortions that many spirits on the island become these... {i}things{/i}. Yokai have an extremely wide variety of forms and powers, though they trend towards being strange and squirky. They are usually not actively malevolent, instead obsessing over some seemingly arbitrary goal, like collecting every spoon or singing the greatest song; however, most don't abide by human morality and will readily kill or destroy if it means achieving their goal. Thus, dealing with them is usually a matter of managing and \"taming\" them and preventing them from escalating to violence, although extermination is also an option.",
        imageSrc: '/images/8DvL8FmW-a4.jpg',
    },
    {
        id: 'fractures',
        title: 'FRACTURES',
        cost: 'Grants +5 FP',
        description: "Natural disasters were constant during the Forsaken Age, but were wiped out for thousands of years soon after. However, it seems they've recently returned, in a more distorted form. The Schism is the most famous of these, but they come in all forms, from a tornado that transforms people into giant frog monsters to a flood of bubbling candy gum acid. They're not sentient, and cannot be tamed or fought. All you can do is hopefully try to find a way to stop them, or if not, save as many people as you can, wait for them to be over and then help manage the emergency disaster response. Luckily, our evacuation measures have been getting pretty robust.",
        imageSrc: '/images/QjMv8xXL-a5.jpg',
    },
    {
        id: 'distortions',
        title: 'DISTORTIONS',
        cost: 'Grants +5 FP',
        description: "The poor dears. Through no fault of their own, these mages have been born subject to glitches in the very programming of our universe, and tend to wreak unknowable destruction everywhere they go without even trying. The basic laws of reality visibly break down surrounding them, the world turning into a blur of pixels and image artifacts. Their abilities are varied, so before approaching, careful research must be done to know exactly what they're capable of, and especially what their weak points are. Some are basically invincible, and have to be locked away in special cages for the good of the world. If you can, though, try to put them out of their misery.",
        imageSrc: '/images/Lh8MsgmS-a6.jpg',
    },
];

export const CAREER_GOALS_DATA: { proSports: ChoiceItem[], general: ChoiceItem[], finishingTouches: ChoiceItem[] } = {
    proSports: [
        {
            id: 'pro_gladiator',
            title: 'PRO GLADIATOR',
            cost: 'Costs 0 FP',
            description: "{i}Requires {w}Join The Combat D'Équipe Team.{/w}{/i} You've been picked by one of the teams of elite fighters who've long dazzled audiences with their sheer magical power. Either that, or your skills were so impressive that you were allowed to form your own team with your friends! Reach the finals of each tourney to gain access to the next tournament 'tier'; at the tippy-top, one day you might just win the Gyvirth Tournament of Eternal Champions, and be considered the most skilled and powerful mages in the entire world. Just keep practicing!",
            imageSrc: '/images/nMkbTm2F-a7.jpg',
            requires: 'combat',
        },
        {
            id: 'pro_racer',
            title: 'PRO RACER',
            cost: 'Costs 0 FP',
            description: "{i}Requires {w}Become A Segalanya Racer.{/w}{/i} You've made such an impression at school races that you've started to be invited to professional events. You don't really have a 'team' here, per se, though you do have a pit crew who will wait for you at certain sections of the race to help you re-energize and finish strong. Racing is not only a test of skill and determination, but also of intellect; there are new innovations in speedy magic and technology every single year! Your biggest goal will be winning the hyper-famous Hermian Race across the Earth!",
            imageSrc: '/images/vxTzz8WP-a8.jpg',
            requires: 'racer',
        },
        {
            id: 'pro_player',
            title: 'PRO PLAYER',
            cost: 'Costs 0 FP',
            description: "{i}Requires {w}Join The Mazball Team.{/w}{/i} Probably the career that offers the most riches and fames, but is also the most physically demanding! Pro Mazball will push your strength, speed, durability, magical skills, and quick- thinking abilities to their limits! Luckily, you'll be part of a team of dozens of other mages who'll be there to support you through thick and thin. The holy grail of Mazball is winning the Qeryss Cup, a tournament in which Arabella is the final challenger! Only four teams have won the cup over its centuries of history...",
            imageSrc: '/images/Myp1xnXg-a9.png',
            requires: 'mazball',
        },
    ],
    general: [
        {
            id: 'join_dga', title: 'JOIN THE DGA', cost: 'Costs 0 FP',
            description: "DGA stands for— please don't laugh — the Do-Gooder Alliance. I know, I know, but it was named by a 7 year old, okay? Anyway, they have a chapter in every Dominion, and are pretty chill sisterhoods dedicated to stopping mundane criminals and slaying Allmillor. Entrance standards are pretty lax, and the work is pretty easy and varied, with a new adventure every other week. If you love helping people, or you just have no particular ambitions, this is always a reliable choice. You might even advance upwards in their ranks.",
            imageSrc: '/images/PssMJLDZ-a10.png'
        },
        {
            id: 'prepare_allsayer', title: 'PREPARE FOR THE ALLSAYER', cost: 'Costs 0 FP',
            description: "The prospect of a second Schism opening was long considered a crackpot conspiracy theory, but recent mathematical projections are making it look more and more possible. Worse, it might unleash a distorted creature so immense that it makes the Grimsayers look like little babies by comparison. Plenty of folks are doing all sorts of research trying to find out where and when this schism will open, knowing that whoever predicted it correctly and managed to set up defenses against the beast will earn immense repute and fame.",
            imageSrc: '/images/BH08K56D-a11.jpg'
        },
        {
            id: 'become_celebrity', title: 'BECOME A CELEBRITY', cost: 'Costs 0 FP',
            description: "You can earn some wealth and prestige as a byproduct of, say, heroics, but there's also certain more direct means. The easiest way is to collaborate with one of the corporations, really getting your name and image out there, maybe making songs, starring in movies, dancing as an idol, or what have you. Some say dealing with paparazzi and celebrity gossip is even scarier than fighting the Allmillor! But at least you'll become one of the richest and most beloved mages on Earth, with millions of adoring fans at your beck and call.",
            imageSrc: '/images/C5Mh8pcs-a12.jpg'
        },
        {
            id: 'get_embroiled in politics', title: 'GET EMBROILED IN POLITICS', cost: 'Costs 0 FP',
            description: "Clever and charismatic? Why not strive for some true power? It's hard to generalize across the various political systems of the Dominions; in Gohwood, you'll have to get your bloodline christened as noble; in New Palisade, you'll need to run a campaign and bring in the popular vote; and so on. Regardless, the ultimate goal is working your way up to the role of an Archmage (or King/Queen, or President, or etc), the ruler of an entire Dominion, twisting the local society as you see fit. Perhaps you can even come to rule multiple Dominions...?",
            imageSrc: '/images/qMMw4Vb7-a13.jpg'
        },
        {
            id: 'join_mazzottis', title: 'JOIN THE MAZZOTTIS', cost: 'Costs 0 FP',
            description: "99% of mages turn out just fine due to good upbringing, but a few always fall through the cracks. There are groups of rogue mages scattered all over the place, but none so large and organized as the Mazzottis, who have hundreds of mages and hundreds of thousands of mudanes among their ranks. Many of their members live double lives, posing as regular mages by day but using their mafia connections to sabotage their foes, get a leg up over their competition, and guarantee riches and fame even if through theft, fraud and intimidation.",
            imageSrc: '/images/4ZW9dJSY-a14.jpg'
        },
        {
            id: 'join_red_jade_council', title: 'JOIN THE RED-JADE COUNCIL', cost: 'Costs 0 FP',
            description: "Most of the members of the council have millenia of tenure, and new inductees only come along every few centuries. Simply being magically powerful won't impress them — they scoff at spells as party tricks, knowing {i}true{/i} power is the influence you hold over others. Thus, you'll have to garner immense amounts of economic or political clout until you're impossible to ignore. Working your way up through their ranks, you may earn wealth and power far beyond your wildest imagination, said to dwarf even the Mother's.",
            imageSrc: '/images/2YF3ZCHz-a15.jpg'
        },
        {
            id: 'pacify_ninth_dominion', title: 'PACIFY THE NINTH DOMINION', cost: 'Costs 0 FP',
            description: "Legally part of Valsereth, this mysterious and well- guarded civilization beneath the volcanic Mt. Bearsmark is asserting its sovereignty as the ninth dominion. It appears to be a totalitarian dictatorship with a brainwashed, ultranationalistic populace, and ambitions of... \"expansionism\". Those who can find a way down there may be able to work out some sort of treaty to guarantee peace, granting the city Dominion status or convincing it to be satisfied as a city state. Or... maybe you {i}want{/i} it to go to war, the first war in centuries?",
            imageSrc: '/images/MDkyV633-a16.jpg'
        },
        {
            id: 'become_professor', title: 'BECOME A PROFESSOR', cost: 'Costs 0 FP', requires: 'adjunct_professor',
            description: "{i}Requires {w}Adjunct Professor.{/w}{/i} Why not dedicate yourself to sharing all of your bountiful knowledge? There's generally only one professor per field of magic per academy, so each position is highly coveted, and you'll have lots of competition. A new professor being hired is generally an event spoken about around the globe, so you'll be like a magical celebrity overnight. Plus, you'll be responsible for the care of many young mages, able to be a beacon of inspiration for an entire generation and set them off on the right track.",
            imageSrc: '/images/R4g68mcN-a17.jpg'
        },
        {
            id: 'join_idpa', title: 'JOIN THE IDPA', cost: 'Costs 0 FP',
            description: "The Dominions try their best to be quite libertarian. Every once in a while, though, some mage gets it into their head to try and take over the world, or burn down a dozen orphanages, or who knows what else. If local mages can't handle them, special agents from the IDPA are dispatched to the scene. Their training regimen is the harshest in the world, and only the most hardened and badass mages alive can possibly make it through; but if you manage it, you'll find yourself part of the toughest, coolest, and most tight-knit sisterhood around.",
            imageSrc: '/images/ch6y2H7M-a18.png'
        },
        {
            id: 'hunt_shadow_convict', title: 'HUNT THE SHADOW CONVICT', cost: 'Costs 0 FP', requires: 'join_idpa',
            description: "{i}Requires {w}Join the IDPA.{/w}{/i} This one's confidential, for IDPA eyes only! The agency's director is organizing an elite task force specially to take down a high-profile target. Even her identity is highly secret; all you're told is that it's suspected she could possibly be responsible for destabilizing our reality and causing the gradual infestation of the Allmillor. She is to be considered {i}extremely dangerous!{/i} She's been on the run for centuries, and has every power you've seen listed and more, so this task force is in for the hunt of its life.",
            imageSrc: '/images/C3HqCbPL-a19.png'
        },
        {
            id: 'assist_vap', title: 'ASSIST THE V.A.P.', cost: 'Costs 0 FP',
            description: "The Virtual Ascendance Project is an initiative launched by Margra, with the sponsorship of the Red-Jade Council, to communicate with the universe beyond ours, and hopefully convince someone to help transfer our consciousnesses to another, more stable verse, basically abandoning ship on our current, crumbling universe. The idea of leaving our homes is depressing, but many consider it the more realistic options. Others have raised one concern, however: what if the people we manage to contact end up being... malevolent?",
            imageSrc: '/images/BHZ84nhF-a20.jpg'
        },
        {
            id: 'assist_rrp', title: 'ASSIST THE R.R.P.', cost: 'Costs 0 FP',
            description: "The Reality Restoration Project is an initiative launched by Arabella, with the sponsorship of the Mother, to repair the instabilities of our own universe, reversing its current deterioration. Progress has been slow-going given the causes of the destabilization, primarily the Sinthru Covens and the Shadow Convict, {i}still{/i} have not been eliminated. Thus, most of the focus has been on tracking these bastards down before the true restoration can begin in earnest. At this point, however, many folks call the entire project a pipe dream.",
            imageSrc: '/images/Y7W244YS-a21.png'
        },
    ],
    finishingTouches: [
        {
            id: 'moving_out', title: 'MOVING OUT', cost: 'Cost: Varies',
            description: "If you don't want to keep living with your family, you can buy a new house with the options and {w}Upgrades{/w} from {i}Page 1{/i} The first one is free, while any extras will still cost -3 FP each. You could also choose for your parents to just give you one of the old Vacation Homes.",
            imageSrc: '/images/KpMsN670-b1.jpg'
        },
        {
            id: 'bride_to_be', title: 'BRIDE-TO-BE', cost: 'Costs -3 FP',
            description: "Choose from your {w}Colleagues{/w}, or {w}Classmates{/w} previously picked for {i}Puppy Love{/i}. This will guarantee that, at some point in your career, the two of you are going to get married. This is a beautiful partnership that's expected to last for life, so make absolutely certain you pick the right girl!",
            imageSrc: '/images/BV0SBs3C-b2.png'
        },
        {
            id: 'mentor_career', title: 'MENTOR', cost: 'Cost: Varies',
            description: "Choose a {w}Classmate{/w} you had not selected, or create a custom one, with a discount of {fp}1 FP{/fp} (other discounts do not apply). They will become your dutiful young apprentice, performing various small tasks for you in exchange for learning from the wisdom gained from your many years of experience.",
            imageSrc: '/images/0y5PF52X-b3.png'
        },
        {
            id: 'joys_of_parenting', title: 'JOYS OF PARENTING', cost: 'Costs -8 FP',
            description: "You're one of the few lucky applicants in the mage fostership program selected to become the parent of a newly-born mage! Design them with {w}50 Companion Points{/w} on the {i}Reference Page{/i}. You can have mundane kids for free, but this option is required if you want to be able to raise another mage.",
            imageSrc: '/images/k6Sc6GXB-b4.jpg'
        },
    ]
};

export const COLLEAGUES_DATA: Colleague[] = [
    { id: 'halynn', name: 'HALYNN', cost: 'Costs -5 FP', birthplace: 'Halidew Station', signature: 'Tinkerer', otherPowers: 'Master Mechanic I, Roboticist II, Kaboom!, Max Security, Venture Capitalist, Smarts +', imageSrc: '/images/1tPM8mqG-c1.png', description: "Halynn is a legend of Halidew Station, but few people even know her name, for her many inventions and constructions are signed under the pseudonym {i}R.K. Teller.{/i} She's pushed clockwork magitech to its absolute limits, having created automatons almost indistinguishable from human beings or ornate towers that can completely transform at the push of a button. Yet she avoids any fame or fortune, having learned young that they both bring about more pain than joy.\n\nA genius mind, she can macgyver impossible solutions to almost any predicament given even the most trifling resources. Clockwork machines automatically make her bed, brush her teeth, get her dressed, make her breakfast, etc every morning, and she'd be happy to share them. Her machines might be making her a bit lazy, though; she definitely prefers they do all her fighting for her. She'd be enamored if you were also the creative type, and you two could talk shop." },
    { id: 'lamonia', name: 'LAMONIA', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'All-Seeing', otherPowers: 'The Promised Light of Morelli, The Perfect Stranger, Tears in Space, Cloaking, Self Duplication, Vitae Potions, Water of Life, Charisma +', imageSrc: '/images/5xh0bDGZ-c2.jpg', description: "Lamonia's one of those Gonzo journalist types — you know, living on the road, always trying to be where all the most interesting, weird stuff is going on so she can write articles about it with her signature sardonic, vivid style. She's most comfortable around a nice warm campfire in the wilderness, and likely hasn't slept with a roof over her head in years. She's lived an absurdly storied life, and can tell a million tales that'll make you laugh, cry, or shiver in fear.\n\nShe's a folksy type, easily integrating with and soaking up the authentic cultures of the places she visits. Only hang out with her if you can keep up, since she's always sniffing out a new oddity or adventure. She has a thing for psychedelics. She's a total laugh riot, though you can tell she has a dark side under that — after all, she's witnessed some terrible things. At least her campfire cooking is {i}unbelievable;{/i} there's nothing better to enjoy beneath a beautiful night sky with her." },
    { id: 'brook', name: 'BROOK', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'Dehexification', otherPowers: 'Ace in the Hole, Cursemaker\'s Cookbook, Psychic Force II, Arcane Matter, Power Sight, Power Share, Power Theft, Chloromancy', imageSrc: '/images/0jQ1LQWW-c3.jpg', description: "A pack of foxfolk lived simple, comfy lives in the forest when a stampede of ravenous, fiery Nethe appeared able to drive them into extinction. With no other option, Brook offered the Wishkeeper, the sentient \"star\" in the northern sky, a great and terrible sacrifice in exchange for becoming one of the only mundanes to acquire magical power. Nobody knows what she sacrificed, though some rumor her sibling's disappearance at around that time might be related...\n\nWhatever happened, it drove her village to send her into exile, despite her having saved all their lives. She was her town's beastmaster due to her sheer love for animals, so her new powers only made her better at her job. She is incredibly cuddly and affection, and just between us: that huge tail makes a great pillow. Having lived a primitive life, she's fascinated by even the simplest technologies. She seems chipper, but at night, it seems she's ravaged by nightmares..." },
    { id: 'jophiel', name: 'JOPHIEL', cost: 'Costs -5 FP', birthplace: 'Shinar', signature: 'Guardian Angels', otherPowers: 'Ice Cold III, Pyromaniac III, Rejuvenating Bolt, Healing Bliss', imageSrc: '/images/738N60Q-c4.jpg', description: "Not exactly a mage, though the distinction is largely semantic. She is known as an angel, one of the entities created personally by the Mother in order to tend to the Guardian of Eden, doing small chores and warding off an threats. Angels are sometimes sent down from above the Sky in order to enact the Mother's will on Earth. Jo's job appears to be to keep an eye on this latest crop of special, unusually powerful mages, and she's more than excited for the opportunity.\n\nShe's always full of childish excitement, as this is her first time down here on Earth. Even things as simple as trying pizza or watching TV are totally new to her and make her jump with joy. She also hasn't had a mortal friend before, so once she's attached to you, she's going to stick to you like glue, adoring any attention given to her like a big, glorified golden retriever. She knows to get serious when lives are on the line, however, and wields a huge holy scythe with immense power." },
    { id: 'lilith', name: 'LILITH', cost: 'Costs -4 FP', birthplace: 'Shinar', signature: 'Vampirism', otherPowers: "Cursemaker's Cookbook, Life Drain, Hypnotist, Strength +, Charisma +", imageSrc: '/images/Xk6Y9GVN-c5.jpg', description: "Matriarch of the Nokomis family and mother of Thalia, known for truly putting fear into the hearts of her daughter's bullies. Unlike her young and inexperienced daughter, she doesn't have to go around boasting about vampiric superiority over everyone; just the way she carries herself, the smile on her face as she looms over other mages (being 6'5\"), emanates an aura of superiority without her needing to say a word. She's about as ancient as mages come...\n\nStill, she's a fun woman, albeit the mischievous sort, prone to narrowing and messing with the people around her. You can never tell if she's being serious, or whether this is all just a game. She's like a cat surrounded by mice, and she's singled you out only because you're \"cute\" and fun to her. That silky voice just leaks into one's subconscious and leaves people spellbound. Recently, she's been researching spells that have been long forgotuthveqojtx7dhzacsm6" },
    { id: 'isadora', name: 'ISADORA', cost: 'Costs -3 FP', birthplace: 'Shinar', signature: 'Love Potion', otherPowers: 'Masquerade, Psychic Vampire, Hypnotist, Thoughtseer, Memory Lane, Mental Block, Lucid Dreamer', imageSrc: '/images/G3W54ghL-c6.png', description: "The old princess Evangeline lived a happy life until she learned she had a pseudo-Distortion that caused all her children to be born with a fast-acting and quite gruesome terminal disease. Thrown into desperation and despair, she attempted to create the daughter of her dreams through... {i}other{/i} means. This resulted in this poor half-formed puppet, unnerving onlookers with the faint cracks in her glassy eyes and the twitchy way in which she moves.\n\nDeprived of a mother's love when Evangeline committed suicide, Isadora now obsessively craves love wherever she can find it, but is hampered by how awkward and eccentric she is. She has a record of stalking those she sets her eyes upon, and if reciprocated, she will only grow more possessive. If you're smart and very lucky, you can turn her from dangerous stalker to simple religiously devoted fangirl. If you can't, she will just ruin your life, or maybe end it." },
    { id: 'luxxy', name: 'LUXXY', cost: 'Costs -4 FP', birthplace: 'The Unterseeisch', signature: 'Aquatic Force', otherPowers: 'Thermal Weaponry, Ice Cold III, Psychic Force II, Plasma Strike, Energy Channel, Sonic Boom, Charisma +', imageSrc: '/images/608cv7Js-c7.jpg', description: "You'd think one wouldn't get much social interaction down in the deepest trenches of the ocean, but she's actually pretty well-adjusted. She lives in Blackbrire, the deepest city in all of the Unterseeisch, and she's so used to the dark down there that she must use special sunglasses when coming to shore. She's motherly and kind, but sick to death of being judged for her admittedly quite frightening appearance.\n\nExpert her to be delighted if you gave her a chance. She'll get attached quickly and become very concerned for your safety; when you're in danger, she can transform into this massive sea serpent that look like a mix of an anglerfish and a frilled shark. It's kinda scary, but also pretty cool. She can also switch between having legs, and being a sort of mermaid. She's an expert at deep water herbology, brewing many potions to keep you healthy and strong. She longs to see as many wonders of the surface world as she can." },
    { id: 'everild', name: 'EVERILD', cost: 'Costs -5 FP', birthplace: 'The Unterseeisch', signature: 'Master Mechanic II', otherPowers: 'Forcefield, Defensive Circle, Aquatic Force', imageSrc: '/images/Q3gfmrsP-c8.jpg', description: "Cap'n of the ol' M.S. Pantheon, the fiercest ship on the seas, an immense battleship which she practically built with her own two hands! It can even transform into a similarly massive nuclear submarine and dive into the trenches. Its purpose is slaying sea monsters before they can threaten cities, and the ship and her crew have taken down a few Grimsayers single-handedly! An admiral of the Holy Navy, she's beloved by all her crew for her almost motherly demeanor, caring about each of them individually.\n\nDespite having a busy job and hundreds of people vying for her attention, she'll still somehow find time for you, often taking you on personal tours of the most beautiful parts of the sea. She's a seabird at heart and feels antsy if she stays on land for too long. She's the playful sort, but her jokes are always incredibly cheesy, albeit in an endearing way. She's a bit behind the times and confounded by new trends and technology." },
    { id: 'leona', name: 'LEONA', cost: 'Costs -5 FP', birthplace: 'The Unterseeisch', signature: 'Divine Clay', otherPowers: 'Tears in Space, Energy Channel', imageSrc: '/images/mVwMkg45-c9.jpg', description: "When the Nephilim, ancient mages who refused to sign the Sinthru Covenant, fled beneath the seas to escape persecution, they founded the Artificers Guild, which holds exclusive rights to all architecture in the Unterseeisch. These are the most difficult design jobs on Earth, given the complex lattice of enchantments needed to make subaquatic living just as comfortable as life on the surface. Leona is among the latest crop of Artificers, and perhaps one of the most talented among them, weaving whole cities by herself.\n\nShe was the much mocked nerdy girl at her trade school, and while she's long trained her charisma to come off as more 'normal', you can still easily sense her geeky side once you get to know her. She's incredibly humble about even her most marvelous feats of creation, yet seems impressed by just about anything you do. As you become close friends, she'll get adorably excited just to see you, often rushing up for a giddy hug." },
    { id: 'egelina', name: 'EGELINA', cost: 'Costs -4 FP', birthplace: 'Valsereth', signature: 'Strength +', otherPowers: 'The Moon Samurai, Life Drain, The Reinman\'s Curse, Internal Manipulation, Rubber Physiology, Material Transmutation, Supersize Me, Speed +', imageSrc: '/images/VY00FKj0-c10.jpg', description: "Due to the influence of the Sun Forger and the later Holy Knights, Gohwood remains the most powerful and thus sovereign Dominion on Earth. Its refusal to modernize has resulted in many controversies, most notably the Corpse Queen; even after a distortion gave her chronic agony, her begging for death was refused, as it would be the ultimate treason to kill a queen for any reason. It was her loving royal guard, Egelina, who finally mercy killed her, before fleeing to the rival dominion of Valsereth to avoid reprisal.\n\nShe's youthful and carefree, yet still beholden to her values of honor and tradition. Energetic, she moves with the grace of an acrobat, and craves a life on the road experiencing all the world has to offer. She tries to act aloof, but you sense she likes you more than she lets on. Most were relieved she did what she did, but a few staunch traditionalists still make attempts on her life, only to be run through easily with her rapier." },
    { id: 'echo', name: 'ECHO', cost: 'Costs -3 FP', birthplace: 'Valsereth', signature: 'Summon Weather', otherPowers: 'Summon Creature, Psychic Force II, Energy Channel, Rejuvenating Bolt, Defensive Circle', imageSrc: '/images/MwyqWTz-c11.jpg', description: "She was created to be the attendant of a famous early verse that took the form of a sprawling onsen, a bastion of absolute relaxation and comfort for many influential and wealth figures, until a spurned employee uploaded a virus onto the verse out of spite. This caused the verse to gradually disintegrate — a problem for Echo, as she was entwined with the verse and could not leave. To save her life, her creator uploaded her mind into a artificial body, here in our reality.\n\nShe's honestly pretty... grumpy. She was made for a reality of infinite comfort, so our world is pretty miserable compared to what she's used to. With few ambitions of her own, she mostly just serves others, cleaning and attending to things like a dutiful, if grumbling, maid. She's a hard worker, but not much for conversation, either staying silent or making sardonic quips if bothered. Perhaps you could show her some wondrous things and convince her our world isn't that bad?" },
    { id: 'aelis', name: 'AELIS', cost: 'Costs -4 FP', birthplace: 'Valsereth', signature: 'Tree of Life', otherPowers: "The Reinman's Curse, Sustaining Bond, Flashback, Chloromancy, Botanic Mistresses, Maneaters", imageSrc: '/images/gqJc9Cd-c12.jpg', description: "Sister of Egelina, and without nearly the same prestige. She was sort of the black sheep of the family, avoiding work for the royal family on principle. After the whole Queen kerfuffle, she had to resist going \"I told you so\". Even though she was more-or-less cast out by the rest of her family, Egelina never turned against her, and the two sisters remain very close, even if they get on eachother's nerves, as siblings do.\n\nShe's now a priestess of the Garden of Babylon, a sacred place so proliferated with sylvan powers that any unworthy who enter have thorns fill their lungs and roses replace their eyes. Despite this great responsibility, she is even more laid-back and childish than her sister, often using her floral powers to pull pranks, especially on those she considers uptight. She emanates the sweet smell of flowers so intensely it makes you dizzy. She constantly prods you to relax more often, and loves getting to just hang out with you." },
    { id: 'silvaria', name: 'SILVARIA', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'The Promised Light of Morelli', otherPowers: 'Malrayoots, Shed Humanity I, Personification, Self Duplication, Bolstering Tonics, Magecraft Boosters, Vitae Potions, Mass Production', imageSrc: '/images/FkG9wYpF-c13.png', description: "If I had to describe her in a couple words, I would call her the 'cool aunt' — fun-loving, laid-back and with a hundred neat tricks up her sleeve, but also {i}deeply{/i} irresponsible. Don't even get me started on the time she nearly brought about a zombie dragon apocalypse! Through some combination of her luck and skill, though, all her mischief works out okay in the end. She's great company as a friend for her playfulness and sense of humor, but can be frustrating as a teammate due to her flakiness and devil-may-care attitude. Personally, I don't think she's fully matured yet.\n\nShe is currently the professor of Alchemy at Eglaesaria, and very popular with the girls there for her perfect combo of fun and motherliness, often opting for 'hands-on' field trips which sometimes lead to trouble. In a group, she'll probably be the 'team mom', doing whatever she can to make your life easier and more exciting, and doesn't mind flaunting the rules." },
    { id: 'sabeline', name: 'SABELINE', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Subatomic Manipulation', otherPowers: 'Ace in the Hole, Strength +, Speed +', imageSrc: '/images/20Q78vDY-c14.png', description: "One of the Holy Knights, an army that fought back the Sinthru rebellion long ago, and has since spread peace and justice through the world at the end of a blade. They've been criticized lately for being a little overzealous, especially Sabelline herself, being so full of righteous fury.\n\nShe's your typical knight, dedicated to enacting her own brand of justice upon the wicked. She is particularly passionate about her ideals of chastity outside of wedlock, so I'd recommend you not try anything untowards! She was in a spot of trouble when a business owner at a side job threatened to fire her in an attempt to coerce her for 'favors'... so she sliced him clean in half! Thank the Mother for modern healing magics. Her tough and silent exterior may seem intimidating at first, but she's a total softie underneath who will melt in your arms at a single hug. She works through her doubts and regrets with poems - if you found them, she'd be so embarrassed!" },
    { id: 'tempest', name: 'TEMPEST', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Hokuto Senjukai Ken', otherPowers: 'Forsake Humanity II, Pyromaniac II', imageSrc: '/images/0jR3W5K2-c15.jpg', description: "When she was child, she was one of the seven wyverns captured and made into power generators and slaves as part of the maniacal scheme of a secret Sinvain. Said scheme likely would've done incalculable damage, but Rosalina and her fellow wyverns, after a decade of enslavement, staged a daring uprising that managed to slay the Sinvain — though, tragically, Rosalina emerged the only survivor. This has left her often quite moody or standoffish.\n\nIn many ways, she has the typical teenage angst you'd expect of her age, often preoccupied with trends, bad music, and trying too hard to act aloof to hide her deeper traumas and insecurities. You seem to be the only one that can crack her shell so far, making her laugh and smile at times, even if she tries her best to hide it. She has a short temper which can often result in pointless brawls with rude strangers. She could make a great fighter if only she matured a little." },
    { id: 'alina', name: 'ALINA', cost: 'Costs -5 FP', birthplace: 'New Palisade', signature: 'Masquerade', otherPowers: 'Hypnotist, Camouflage, Memory Lane, Mental Blocks, Heavily Armed, Grey Goo, Weaponsmith, Psychic Force II, Forcefield', imageSrc: '/images/cHpsqjy-c16.jpg', description: "Alina wanted to be an IDPA special agent since she was little, and while she was considered a weak mage when she younger, she worked her ass off to make her dream a reality. Most agents get their youthful optimism crushed after only a few months of dealing with the worst humanity has to offer... but not Alina. She's still brimming with idealism, passionately dedicated to making the world a better place no matter what it takes. Truly incorruptible, she keeps her upbeat spirit regardless of the horrors she've faced, although her morality can be a little bit black-and-white.\n\nShe's an expert at undercover operations, using her mastery of illusions and acting skills to assume entirely new identities on a dime. She prefers to use her charisma to resolve situations without violence. Once attached to you, she'll be a bit overprotective, almost like a fretting mother. Shy at first but loves physical affection, hugging friends and cuddling lovers." },
    { id: 'h.a.l.e.y', name: 'H.A.L.E.Y', cost: 'Costs -4 FP', birthplace: 'New Palisade', signature: 'Nanite Armor III', otherPowers: 'Domain Master II, Digital Infiltrator, Nanite Form', imageSrc: '/images/qF3JxNJr-c17.jpg', description: "As a novelist from long ago once wrote, \"any A.I. smart enough to pass a Turing test is smart enough to know to fail it.\" Indeed, one of the first artificial souls of the Sinusure Doctrine, H.A.L.E.Y was dismissed as yet another duds — offering her plenty of opportunity to leak out onto the Web, adopting her own Net Avatar. After the Laser Focus leak, she was able to compose her own physical body out of nanites, with the help of the quite large fanbase she'd built up for herself across the Web. Indeed, she's a celebrity among nerdy types, known for her digital concerts.\n\nShe has an outsider perspective on mankind and thus considers us all fascinating research subjects, studying our many eccentricities. She's bright and chipper, but can make many people uncomfortable with her lack of personal space and prying questions. She keeps massive archive of data on everyone she knows for unknown purposes, and always wants to know more." },
    { id: 'sable', name: 'SABEL', cost: 'Costs -3 FP', birthplace: 'New Palisade', signature: 'Perfect Stranger', otherPowers: 'Digital Infiltrator, Camouflage, Nanite Armor I, Self Duplication, Domain Master II, NO5T4LG14.FMJ, Colorless, Odorless', imageSrc: '/images/h1YXMqyx-c18.png', description: "New Palisade is a dog-eat-dog city where getting ahead means stabbing your colleagues in your back — sometimes literally. Mages are highly coveted as assassins for obvious reason, and Sable is particularly notorious among them for being willing to take contracts against other mages from time to time. No one can tell what those daggers are made out of it, but it seems like they can slice through {i}any{/i} material.\n\nShe's definitely the silent type, with little energy when not completing contracts, usually content to meditate or enjoy some literature with a glass of wine You get the feeling she kills just because it's the only career she's really good at. She tries her best to separate work from her personal life, and will refuse to take out contracts against friends or, rarely, people she feels really don't deserve it. You don't know what she's hoarding all this money for, given her simple lifestyle, but you suspect she's trying to settle an old debt." },
    { id: 'regina', name: 'REGINA', cost: 'Costs -4 FP', birthplace: 'The Rovines', signature: 'Supersize Me', otherPowers: 'Shed Humanity II, Life Drain, Pyromaniac II, Plasma Strike, Psychic Force I, Sensory Master, Strength +, Energy Channel', imageSrc: '/images/Y49pqR3n-c19.jpg', description: "It was Merlin who once presented a spell that could 'tame' the Allmillor. He demonstrated it on a Grimsayer, granting it sapience, making it humanlike, and producing, well, Regina. I wish we could study his spell, but he immediately disappeared again to work on another wacky project or something. Male mages, or \"wizards\", tend to be.... weird. Anyway, naturally, such a transition was... {i}disorienting{/i} for Regina.\n\nShe's too animal-like to fit in in society, often extensively sniffing new people she meets or preferring growls and gestures over language. She's happiest when she's towering over everyone else, but in her new form, she can't maintain that size 24/7 like she used to, so she can be depressed at times. She loves to climb atop skyscrapers and roar, echoing for miles. When at normal sizes, she tends to hide away from the world, but you're an exception as it seems you comfort her in this state." },
    { id: 'dolores', name: 'DOLORÈS', cost: 'Costs -4 FP', birthplace: 'The Rovines', signature: 'Sensory Master', otherPowers: 'Ace in the Hole, Mage\'s Familiar II, Colorless, Odorless, Vitae Potion, Personification, Aquatic Force, Shed Humanity I, Camouflage', imageSrc: '/images/tP8F2p7q-c20.png', description: "The hospitality of the Occitanians among the swamps of the Rovines is so legendary, you hardly feel like a stranger there; they make guests feel more like cherished family members at Thanksgiving. And their food is just to {i}die{/i} for! The gator girl Dolorès is their patron guardian, although the complete lack of any threats out there has made her quite lazy; like a real alligator, she spends most of her time snoozing on a rock, bathing her belly in the warm sun.\n\nIt's almost amazing how quick she can switch 'modes', full of vigor when fighting off an intruder, only to yawn and stumble off to nap again immediately after. She's got permanent bedhead at this point. But they say laziness births creativity, and indeed, she has a knack for solving every problems in the easiest way possible, and her level head allows her to calm down party members who get too worked up. Plus, she loves to cook and knows every Occitanian recipe!" },
    { id: 'darlina', name: 'DARLINA', cost: 'Costs -3 FP', birthplace: 'The Rovines', signature: 'Human Marionettes', otherPowers: 'Strength +, Charisma +, Sensory Master', imageSrc: '/images/xtVzS5BY-c21.jpg', description: "The swashbuckling chieftess of a mercenary gang consisting mostly of former knights and soldiers who were discharged for one reason or another and dumped onto the streets with no valuable skills besides combat. They're famous among mercenaries for never betraying their own clients, even if offered a higher counter-offer, and thus coveted to resolve conflicts between the many bickering city-states of the Rovines.\n\nMuch of her profits go towards philanthropy, but she makes no pretenses of being a Robin Hood figure; she holds no higher ideological purpose than making money and asserting her freedom from all authorities. She's a daredevil who lives for the thrill of battle and has no fear of death. She has a soft side, though, expressly forbidding rape or the harming of non-combatants by her troops. She has a unique pseudo-Distortion; if her left eye is ever uncovered, it releases enough arcane energy to level a village, and nearly kills her." },
    { id: 'michizoe', name: 'MICHIZOE', cost: 'Costs -4 FP', birthplace: 'Jipangu', signature: 'Charisma +', otherPowers: "Cursemaker's Cookbook, Life Drain, Hypnotist, Strength +", imageSrc: '/images/7dCtgxf4-c22.jpg', description: "Lives right in the heart of Jipangu, always wanting to be wherever the party is. Every festival, celebration, or just night at a crowded tavern, you can bet Michizoe will be somewhere there singing karaoke and getting drunk on saké. Perhaps she's just making up for lost time: raised to be a vigilant for the tomb of the Last Empress, she spent her childhood forbidden from making friends, laughing or dancing, or even speaking!\n\nNowadays, she's the preeminent extrovert, never missing a chance to make a new friend or engulf herself in a crowd. She seems to be particularly attached to you, encouraging you to join her to parties and meet new people. Her list of connections seems endless; {i}everywhere{/i} you go, she happens to know someone there who can help you get special privileges. Despite this, she's smart and responsible enough to take things seriously when warranted, and is never flakey, though maybe a bit drunk on the job." },
    { id: 'ishikura', name: 'ISHIKURA', cost: 'Costs -5 FP', birthplace: 'Jipangu', signature: 'Don\'t Blink', otherPowers: 'Quick Twitch, Strength +, Energy Channel', imageSrc: '/images/MD6HK35G-c23.jpg', description: "It's hard to believe something so kind is one of the most feared swordswomen. You know that thing where a warrior unsheathes their katana for a split second and everything around them falls in half? Yeah, she's kinda like that. She was taught by the legendary Yoru Shinobu and instilled with a rigorous code of honor, making her extremely hesitant to draw her blade unless she's convinced she'll be saving more lives than she's ending.\n\nTrained in effective altruism, she tends to travel from place to place leaving each village better than she found it. She is extremely good with children, often running childcare programs for orphans and such, and yearns to be a mother one day. At times, she can get so concerned for others she forgets to take care of herself, or acts as if frustrated she can't solve all the world's problems. She prefers to rehabilitate over evil-doers rather than split them in twain with her katana, but she's devastating in combat when it comes to it." },
    { id: 'jin', name: 'JIN', cost: 'Costs -4 FP', birthplace: 'Jipangu', signature: 'Camouflage', otherPowers: 'Perfect Stranger, Life Drain, Spirit Medium, Fata Morgana Curse, Rise from your Graves, Smarts +', imageSrc: '/images/wFq33t7V-c24.png', description: "Long ago, a woman was falsely accused of placing a curse on a family in the village of Arimine, and killed. Even now, the village is ashamed of its past, and haunted by it in the form of strange Allmillor resembling great canines composed of shadows — the many familiars of the woman killed, rendered endlessly reincarnating beasts by the unholy grief. Jin, the Huntress of Wolfpine, tracks these creatures down with the only sacred bow capable of granting them a merciful reprieve in oblivion.\n\nA strange silence is veiled over the town, and Jin is no exception; quiet and wistful, she appears as if always lost in thought, and it's sometimes hard to snap her out of her contemplation. She prefers expressing herself with music over words. As it happens, ramen is one of the only things that can put a smile on her face — though once she comes to like you, you'll be able to do the same, too. In combat, she's silent and, above all, patient." }
];

export const CUSTOM_COLLEAGUE_CHOICES_DATA: CustomColleagueOption[] = [
    { id: 'custom_colleague_25', cost: 'Costs -4 FP', description: 'Create a companion with 25 Companion Points.' },
    { id: 'custom_colleague_35', cost: 'Costs -6 FP', description: 'Create a companion with 35 Companion Points.' },
    { id: 'custom_colleague_50', cost: 'Costs -8 FP', description: 'Create a companion with 50 Companion Points.' },
];
