
import type { School, ChoiceItem, Classmate, CustomClassmateOption } from '../types';

export const SCHOOLS_DATA: { [key: string]: School } = {
  halidew: { id: 'kaliam_tech', title: 'KALIAM TECH', description: "The forefront of magitechnological innovation the world over, almost every modern luxury we take for granted has its roots in Kaliam researchers. Hard-working and ambitious students will fit in well, but lazier sorts may be put off by the often brutal workload. You'll be surrounded by brilliant minds.", costBlurb: "Juathas Sigil: Costs 2 BP less for Blessings administered by Margra.", imageSrc: 'https://i.ibb.co/W4bHtB7F/sch1.jpg' },
  shinar: { id: 'sheol_ academy', title: 'SHEOL ACADEMY', description: "The oldest school of magecraft, Sheol seems strange and impenetrable to new students, but if you apply yourself enough (or have good connections), you can slowly work your way into its ancient, exclusive sororities and discover there's a {i}lot{/i} more going on here meets the eye. There's long-buried secrets hidden around every corner, if you know where to look.", costBlurb: "Sinthru Sigil: Costs 2 BP less.", imageSrc: 'https://i.ibb.co/4wQRPD9B/sch2.jpg' },
  unterseeisch: { id: 'st_lucindas', title: "ST. LUCINDA'S SCHOOL", description: "A small town in itself, St. Lucinda's is probably the most laid-back and fun school out there, with quite relaxed standards and lots of partying. While students here are often stereotyped as lazy, there's actually plenty of opportunities for more ambitious student to learn a lot from the school's wise Sea Saints.", costBlurb: "Juathas Sigil: Costs 2 BP less for Blessings administered by Fidelia.", imageSrc: 'https://i.ibb.co/FqLwSkw3/sch3.jpg' },
  valsereth: { id: 'strasmara', title: 'STRASMARA', description: "This Earth's equivalent of the Ivy League. This school boasts some of the smartest and most powerful mages in the world, but its students are stereotyped as snobbish and egotistical. It's the forefront of efforts to research ways to push the Blessings to their limits, and is even the institution that hosts the Irrun Gauntlet. Can be stressful due to its high standards.", costBlurb: "Xuth Sigil: Costs 3 BP less.", imageSrc: 'https://i.ibb.co/tpKN3jCW/sch4.png' },
  gohwood: { id: 'eglaesaria', title: 'THE EGLAESARIA', description: "Formed by a group of powerful dragons many millennia ago; only one of these dragons still lives, serving as the academy's massive, imposing headmaster. It prizes a more simple, combat-centered approach to magic, and many of the greatest warriors in history were taught here. Honor is paramount.", costBlurb: "Juathas Sigil: Costs 2 BP less for Blessings administered by Arabella.", imageSrc: 'https://i.ibb.co/TB1z4y1d/sch5.jpg' },
  palisade: { id: 'triumph_towers', title: 'TRIUMPH TOWERS', description: "Tied for the tallest towers in New Palisade, so much so that they use portals instead of elevators. This is a private school known as the spot for rich kids, and life here is the pinnacle of opulence and luxury, although it can sometimes feel unnervingly corporate. Social influence is treasured here, so it's a good choice for those who want to establish some celebrity status.", costBlurb: "Lekolu Sigil: Costs 2 BP less.", imageSrc: 'https://i.ibb.co/Y4CG2h57/sch6.jpg' },
  rovines: { id: 'droudnore', title: 'DROUDNORE INSTITUTE', description: "Known for its smokestacks, the Droudnore Institute is perhaps the most modest school, situated on its own spacious private island. Criticized by some for having a less exciting atmosphere than other schools, but it's a perfect choice for more serious students who want to learn very practical magic, and don't want to fret about with theoretical magic like at the Strasmiara.", costBlurb: "Juathas Sigil: Costs 1 BP less.", imageSrc: 'https://i.ibb.co/0RLvt7Td/sch7.jpg' },
  jipangu: { id: 'horikoshi_koko', title: 'HORIKOSHI KOKO', description: "Placed atop Mount Ishikawa, just above the clouds, a variety of charms and hexes make it impossible for all mundanes to ever access. Students tend to get there via portals built in their various shrines. It is steeped in ancient traditions, and constantly alive with fun festivals, parades, ceremonies, and other activities.", costBlurb: "Ruhai (Juathas) Sigil: Costs 1 BP less.", imageSrc: 'https://i.ibb.co/FkLW44SM/sch8.jpg' },
};

export const HEADMASTERS_DATA: ChoiceItem[] = [
    { id: 'waning', title: 'WANING', cost: 'Grants +6 FP', description: "They were a legend centuries ago, but over time, their competence has only dwindled. Now, the school is chronically unorganized and mismanaged, with them only kept due to their influence and long tenure.", imageSrc: 'https://i.ibb.co/W4ZzC7qL/head1.jpg' },
    { id: 'stringent', title: 'STRINGENT', cost: 'Grants +3 FP', description: "They hail from the old-fashioned 'spare the rod, skip the child' ideas of schooling. They're just as competent, if not moreso, but their sternness and short temper means you definitely don't want to earn their ire.", imageSrc: 'https://i.ibb.co/yrT9Y8b/head2.jpg' },
    { id: 'competent', title: 'COMPETENT', cost: 'Costs 0 FP', description: "They're youthful in how laid-back and friendly they are, but show their age in their great wisdom and ability to manage the busy school with ease. They tend to work in the background, rarely taking an active role.", imageSrc: 'https://i.ibb.co/YF9M4wcf/head3.jpg' },
    { id: 'sagely', title: 'SAGELY', cost: 'Costs -3 FP', description: "With centuries of knowledge and experience, your education will be cultivated to a razor point under their management. They overflow with wisdom, and you'll look forward to your rare conversations with them.", imageSrc: 'https://i.ibb.co/35bdq6kX/head4.jpg' },
    { id: 'venerable', title: 'VENERABLE', cost: 'Costs -6 FP', description: "A legendary scholar revered around the world, you are almost awed at their brilliance. Despite their prestige, they make a point to dedicate time to personally assisting and bonding with students.", imageSrc: 'https://i.ibb.co/TqN04nx1/head5.jpg' },
];

export const TEACHERS_DATA: ChoiceItem[] = [
    { id: 'mama_bear', title: 'THE MAMA BEAR', cost: 'Costs -3 FP', description: "Eminently motherly and protective, she seemingly has infinite free time to devote to personally bonding with each student, not only educating them but offering support and help with all of their problems.", imageSrc: 'https://i.ibb.co/3y9C7tRv/teacher1.jpg' },
    { id: 'entertainer', title: 'THE ENTERTAINER', cost: 'Costs -2 FP', description: "Their classes feel less like lectures and more like uproacious comedy bits, yet you still learn a ton! Their teaching methods are brilliant and engaging, and they'll make sure you get through class stress-free.", imageSrc: 'https://i.ibb.co/5WBTBSrc/teacher2.jpg' },
    { id: 'sweetheart', title: 'THE SWEETHEART', cost: 'Costs -1 FP', description: "A walking bundle of pure wholesomeness, bringing fresh-baked cookies to class and acting like a mom more than a teacher. The problem is, they're so coddling it can feel like you aren't learning as much...", imageSrc: 'https://i.ibb.co/4wCqDfWd/teacher3.jpg' },
    { id: 'professional', title: 'THE PROFESSIONAL', cost: 'Costs -1 FP', description: "They're not your friend, they're your teacher. They will be strict, but fair, and if you're willing to put in the effort, you'll find you learned more in their class than any others. Just don't expect any coddling.", imageSrc: 'https://i.ibb.co/S4c2M2X3/teacher4.jpg' },
    { id: 'geek', title: 'THE GEEK', cost: 'Costs 0 FP', description: "They're super passionate about their chosen field, and their class is highly organized and optimized. However, they can sometimes have trouble expressing their knowledge, and may move too fast.", imageSrc: 'https://i.ibb.co/5hrs8qm5/teacher5.jpg' },
    { id: 'free_spirit', title: 'FREE SPIRIT', cost: 'Costs 0 FP', description: "Super kind, almost overly so, and a bit disorganized and fast-and-loose with their teaching. Often experiments with teaching techniques, which sometimes work extremely well, and sometimes go terribly.", imageSrc: 'https://i.ibb.co/nqrggCS0/teacher6.jpg' },
    { id: 'oddity', title: 'THE ODDITY', cost: 'Costs 0 FP', description: "Your teacher actually isn't human, but a fascinating or mystical creature of some sort! Sure, this will result in rather questionable effectiveness at teaching... but in my opinion, the awe and novelty are worth it.", imageSrc: 'https://i.ibb.co/604RGN2T/teacher7.jpg' },
    { id: 'inexperienced', title: 'THE INEXPERIENCED', cost: 'Grants +1 FP', description: "You can tell they're trying their best, but they're obviously brand new at this. They're often shy and nervous in front of class, and tend to be pretty clumsy and unorganized. Maybe they'll get better, with a little help?", imageSrc: 'https://i.ibb.co/4ZtTWGrp/teachernew1.jpg' },
    { id: 'sleeper', title: 'THE SLEEPER', cost: 'Grants +2 FP', description: "They're likeable, at least... but they're just so tired all the time. Nobody knows why, but it seriously affects their teaching. Often they'll just have you study amongst yourselves while they nap at their desk.", imageSrc: 'https://i.ibb.co/RkWHLXsT/teachernew2.jpg' },
    { id: 'curmudgeon', title: 'THE CURMUDGEON', cost: 'Grants +3 FP', description: "They've got a nasty temper and zero tolerance for any impropriety, slacking or childishness. They're fine at what they do, but the atmosphere in their class is tense to say the least. Everyone is afraid of them!", imageSrc: 'https://i.ibb.co/LzQcktGR/teachernew3.jpg' },
];

export const DURATION_DATA: ChoiceItem[] = [
    { id: '2_years', title: '-2 YEARS', cost: 'Grants +15 FP, Grants +5 BP', description: "You want to get out the door as quick as possible so you can start getting some hands-on experience! You'll be missing out on a lot of educational opportunities, though.", imageSrc: 'https://i.ibb.co/GqCC6yq/year1.png' },
    { id: '6_years', title: '-6 YEARS', cost: 'Grants +15 BP', description: "The most common length of time by far. This is enough to get students a decent education in whatever will ensure their success in future careers. Considered the goldilocks zone.", imageSrc: 'https://i.ibb.co/R4yLPbnx/year2.png' },
    { id: '10_years', title: '-10 YEARS', cost: 'Grants +20 BP', description: "A more uncommon choice fit for more studious scholars. You will gain new appreciation for your Blessings, though your lack of job experience may be a boon for your competition.", imageSrc: 'https://i.ibb.co/HpBXpjrH/year3.png' },
    { id: '15_years', title: '-15 YEARS', cost: 'Grants +25 BP', description: "By now, you've been here for a majority of your life. It's a second home to you now, but you'll have to say painful goodbyes to the many friends who move on before you.", imageSrc: 'https://i.ibb.co/7xV8dvdq/year4.png' },
    { id: '20_years', title: '+20 YEARS', cost: 'Grants +30 BP', description: "You have officially been lost in the sauce of academia! You'll learn much, but wonder whether your time would've been better suited gaining practical experience out in the field.", imageSrc: 'https://i.ibb.co/d0h4CzY0/year5.png' },
];

export const CLUBS_DATA: ChoiceItem[] = [
    { id: 'combat', title: 'JOIN THE COMBAT D\'ÉQUIPE TEAM', cost: 'Costs -6 FP', description: "Join a team of fighters and battle other teams in the coliseums to ascend through the brackets and win dazzling tournaments! Said coliseums are placed in pocket dimensions that ensure that no fatal or permanent injuries can be suffered by any participants. Almost every goes except Sinthru magic.", imageSrc: 'https://i.ibb.co/TMc2N31j/club1.jpg' },
    { id: 'racer', title: 'BECOME A SEGALANYA RACER', cost: 'Costs -6 FP', description: "Settle disputes on whose method of traveling is fastest, in races that can span from only a mile or so, all the way up to circumnavigating the entire planet! Pretty much anything goes, from flying on a broomstick to soaring on a jet plane. The only rules: no interfering with other racers, and no teleportation.", imageSrc: 'https://i.ibb.co/F4xDmkmp/club2.jpg' },
    { id: 'mazball', title: 'JOIN THE MAZBALL TEAM', cost: 'Costs -6 FP', description: "Kind of like basketball, but imagine it with the 'nets' a half mile apart, and both teams can fly, move fast enough to break the sound barrier, and sabotage eachother with a dizzying variety of spells. Needless to say, Mazball matches are incredibly hard to follow, but entertaining to watch nonetheless.", imageSrc: 'https://i.ibb.co/0y9VLsGD/club3.jpg' },
    { id: 'student_council', title: 'STUDENT COUNCIL', cost: 'Costs -3 FP', description: "Student council president is basically the highest level of power you can have over your peers (short of becoming faculty). Competition is fierce, though! It's good practice if considering a political career.", imageSrc: 'https://i.ibb.co/VWJ0Qw5k/club4.jpg' },
    { id: 'study_hall', title: 'STUDY HALL', cost: 'Costs -3 FP', description: "Let's be honest. \"Study hall\" is pretty much just a pretense for the geeky girls to get together and play tabletop games, eat snacks, and gush about those weird cartoons they make over in Jipangu.", imageSrc: 'https://i.ibb.co/mF8hvrxS/club5.jpg' },
    { id: 'community_watch', title: 'COMMUNITY WATCH', cost: 'Costs -3 FP', description: "{i}Technically,{/i} they're only supposed to be doing stuff like rescuing cats from trees. Off the record, they go out and stop bank robberies and such! They're big on heroics... even if it doesn't always go well.", imageSrc: 'https://i.ibb.co/v6VngtPZ/club6.jpg' },
    { id: 'school_band', title: 'SCHOOL BAND', cost: 'Costs -3 FP', description: "I cannot express in words what magic instruments sound like. Just know it's the kind of sound that moves your very soul. Good way to get fame, too, given they perform for all sorts of major venues.", imageSrc: 'https://i.ibb.co/bgGCZB75/club7.png' },
    { id: 'art_club', title: 'ART CLUB(S)', cost: 'Costs -3 FP', description: "Poetry, painting, knitting... whatever kind of art you're into, I'm sure there's a club out there. See cool art and show off your own works! Creating art is nourishing to the soul, or so I've always heard.", imageSrc: 'https://i.ibb.co/7dMgp7cN/club8.jpg' },
    { id: 'beastmastery', title: 'BEASTMASTERY CLUB', cost: 'Costs -3 FP', description: "Made for students planning to own a familiar, this club's members meet and learn how to train and interact with a wide variety of fantastical creatures. If you like petting animals, this is the best club ever.", imageSrc: 'https://i.ibb.co/VY2pwPdq/club9.jpg' },
    { id: 'outdoorsmanship', title: 'OUTDOORSMANSHIP CLUB', cost: 'Costs -3 FP', description: "A small but extremely friendly bunch of mages who like exploring the far reaches of the world, going on sight-seeing tours through Dominions before stopping to set up cozy little camps in the wilds.", imageSrc: 'https://i.ibb.co/n8qQghpm/club10.jpg' },
    { id: 'fitness_club', title: 'FITNESS CLUB', cost: 'Costs -3 FP', description: "Reaching your potential isn't just about learning! It also requires dedicated practice and training. This club offers endless encouragement and support, helping you to your goals free of judgement.", imageSrc: 'https://i.ibb.co/9kSPpVqq/club11.jpg' },
    { id: 'theatre_club', title: 'THEATRE CLUB', cost: 'Costs -3 FP', description: "Express yourself by writing, dancing, or performing in plays, alongside a super creative and laid-back bunch! This will hone a bunch of skills, with acting teaching you to manipulate and persuade people.", imageSrc: 'https://i.ibb.co/wNWVLkDD/club12.jpg' },
    { id: 'school_nurse', title: 'SCHOOL NURSE', cost: 'Costs -3 FP', description: "The hardest-working bunch around, helping their peers through healing, blessings of reinforcement, counselling, physical training, and etc. Great if you want to learn to be a healer or otherwise support.", imageSrc: 'https://i.ibb.co/rG0DFHQS/club13.jpg' },
    { id: 'night_school', title: 'NIGHT SCHOOL', cost: 'Costs -3 FP', description: "Vampires and werewolves and—scariest of all—goths! The girls that attend night school tend to be quite spooky, but they're nicer than they look. All being outcasts, they stick together like glue.", imageSrc: 'https://i.ibb.co/jkd1yvsX/club14.jpg' },
    { id: 'sukeban_gang', title: 'SUKEBAN GANG', cost: 'Costs -3 FP', description: "A band of juvenile delinquents rebelling against social norms and generally getting into trouble. They're loyal to eachother like a family through thick and thin — there's no other group as close-knit!", imageSrc: 'https://i.ibb.co/cXVxsxdm/club15.jpg' },
];

export const MISC_ACTIVITIES_DATA: ChoiceItem[] = [
    { id: 'mentor', title: 'MENTOR', cost: 'Costs varies, Grants varies', description: "Very lucky and promising mages sometimes get assigned a mentor! These are skilled and experienced mages who will manage your education. Choose a {w}Colleague{/w} from page 5, or create your own, although their {fpx}FP{/fpx} price is doubled. However, you gain {bpx}BP{/bpx} equal to half of the amount of {fpx}FP{/fpx} you had to spend.", imageSrc: 'https://i.ibb.co/jPVVjzph/mis1.png' },
    { id: 'puppy_love', title: 'PUPPY LOVE', cost: 'Costs -1 FP', description: "{i}♬ And they called it puppy looove...{/i} Choose from your {w}Classmates{/w}. What starts as an schoolyard crush can blossom into a relationship that lasts you centuries! You can always try romance, but this option guarantees it will work. How quickly, though, depends on the effort you put in.", imageSrc: 'https://i.ibb.co/hF2LN38F/mis2.png' },
    { id: 'teachers_assistant', title: 'TEACHERS ASSISTANT', cost: 'Costs -5 FP, Grants +2 BP', description: "{i}Requires {w}>10 Years{/w} or greater.{/i} They say the best way to internalize something is to teach it to somebody else. For this reason, as you reach a high level in your discipline, it is a great idea to help a teacher instruct a class! You won't usually be lecturing, but you will be helping the students learn.", imageSrc: 'https://i.ibb.co/rfMp6D38/mis3.png' },
    { id: 'adjunct_professor', title: 'ADJUNCT PROFESSOR', cost: 'Costs -5 FP, Grants +3 BP', description: "{i}Requires {w}>15 Years{/w} or greater, and {w}Teachers Assistant{/w}.{/i} You're basically faculty now! Well, not really. But you're still participating in academic research at the institution, and you're even teaching your very own classes! This is the perfect opportunity to teach and inspire a whole generation of mages.", imageSrc: 'https://i.ibb.co/mVQpXNnm/mis4.png' },
];

export const CLASSMATES_DATA: Classmate[] = [
    { id: 'keeling', name: 'KEELING', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'Subatomic Manipulation', otherPowers: 'Forcefield, Psychic Force II', imageSrc: 'https://i.ibb.co/8LQbDZH8/c1.jpg', description: "What a strange mage she is, with a lower body looking like some sort of giant, sand-bleached serpent. She's quite powerful; if she stares at a mundane with enough concentration, she can turn them into a pillar of sand, or create storms of sand powerful enough to disorient and wound mages. She's thus been set as the guardian of the Labyrinth of Concordia, which contains the sum of the world's knowledge, buried in the annals of the college.\n\nQuite lazy, she naps most of the day away — preferably coiled up tight around somebody, considering people warm and comfy. Hope you don't mind sand in your shoes. She's kind of like a housecat: if you're too pushy, she won't like you, but if you give her space, she can become quite loyal and affection, in her own way. She loves to read, and remembers an impossible amount of trivia. When angered enough, she goes from cute to properly terrifying!" },
    { id: 'starla', name: 'STARLA', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'The Promised Light of Morelli', otherPowers: 'Sustaining Bond, Healing Bliss, Guardian Angel, Vitae Potions, Water of Life, Bolstering Tonics, Smarts +', imageSrc: 'https://i.ibb.co/yFsnGy9s/c2.jpg', description: "The justice system usually balks at capital punishment, preferring rehabilitation, but not even the Mother could coax the vileness from the archlich Elvira. So, she was instead forced to reincarnate, wiping the slate clean — though Starla sees memories of her old self's crimes in occasional nightmares, and is still burdened by the lingering guilt. She's trying to spend this new existence saving lives instead of taking them.\n\nShe's currently the curator at the city's museum, believing those who do not remember the past are doomed to repeat. Very prim and proper, she always dresses like a formal event and can be quite perturbed by crudeness. Bright and passionate, she likes sharing her love of learning with others, and will help immensely with passing your classes and training with new spells. Commonly called an old soul, and loves music from centuries ago. She'll be super proud and excited to show you her museum collection." },
    { id: 'nyla', name: 'NYLA', cost: 'Costs -3 FP', birthplace: 'Halidew Station', signature: 'Roboticist II', otherPowers: 'Tears in Space, Camouflage, All-Seeing, Arcane Matter, Smarts +, Material Transmutation', imageSrc: 'https://i.ibb.co/1Fc6hXg/c3.jpg', description: "Hmm... a tragic case. In Halidew, it is a rite of passage at primary school graduation to create and release an automaton known as a steambird. Nyla and her friend, Lexie, thought they could particularly impress by equipping theirs with a metathermal generator. Sadly, it malfunctioned horribly, and Lexie was killed in the explosion.\n\nShe was much more popular than Nyla ever was, so from then on, fair or not, people branded Nyla the girl whose incompetence cost the city a very beloved mage. She's been a recluse ever since, tinkering with her robots and avoiding everyone else. I hear she internalized what people say and really does blame herself. Such a shame. She used to be a joy! Always making robots to help her friends with even their most minor chores, having them throw parties and performances to entertain everyone in town, skipping around with a goofy smile on her face. If you could get the old her back, you'd have a great friend." },
    { id: 'araminta', name: 'ARAMINTA', cost: 'Costs -4 FP', birthplace: 'Shinar', signature: 'Summon Creature', otherPowers: 'Gathoth Puzzle, Advanced Verse Package, Summon Weather, Natural Environment, Shifting Weather, Artificial Environment, Broken Space, Broken Time', imageSrc: 'https://i.ibb.co/1tjhYst1/c4.jpg', description: "She's not trying to get you to join a cult, is she? We told Araminta. No. More. Cults! I don't care who \"V'arrkra the Forgotten One\" is. I swear, those hermit esotericist families on the outskirts of Shinar believe in the damndest things. Lovely girl otherwise, though. And to be fair, I suspect the reason she gets into those things is partly to help support her poor, beloved grandfather. After his stint in the Sinthrus' hell-verse all those millenia ago, he's just never been the same...\n\nOn that note, she has a verse of her own. And it can't be a terribly pleasant place, judging by the horrid tentacle creatures with a thousand eyes she can bring trawling out of it. But if you're brave enough, feel free to take her up on her offer to join her for a nice pot of tea. She's got a spooky aesthetic, but deep down, I think she's just a sweet girl who desperately wants to be understood. Talking to her, sometimes you do get the feeling she might be onto something..." },
    { id: 'orenda', name: 'ORENDA', cost: 'Costs -4 FP', birthplace: 'Shinar', signature: 'Undead Beast', otherPowers: 'Life Drain, Grasping Dead, Rise From Your Graves, Spirit Medium, Fata Morgana Curse', imageSrc: 'https://i.ibb.co/BVBtCKJk/c5.jpg', description: "She really wants to be a good mage! She's trying her best! But her anxiety gets the better of her, and she often clumsily whiffs her attempts at magic in the most embarrassing ways. At least her wise undead-guardian-turned-father-figure, Xonnan, is always there to pick her up when she's down, even if he can be a bit sheltering (and is probably better at magic than she is). She tries her hardest to live up to her mother, one of the best necromancers in history, hoping to make her proud one day. I think the poor girl is still in denial over the fact her mother doesn't care about her in the slightest...\n\nBeyond that, though, she's fun to hang out with. She's quite geeky, and gets adorably excited when allowed to gush about all of her favorite myths and legends in extreme detail. She'll know the lore of every treasure or ruin you find out on your adventures — provided you can convince her overprotective guardian to let her go out." },
    { id: 'thalia', name: 'THALIA', cost: 'Costs -3 FP', birthplace: 'Shinar', signature: 'Vampirism', otherPowers: 'Hypnotist, Psychic Vampire, Psychic Force I, Strength +, Speed +', imageSrc: 'https://i.ibb.co/n86LWZMX/c6.jpg', description: "Born into the mysterious Nokomis family, a bloodline through which vampirism runs due to an age-old curse. You get the sense she's been bullied for her vampiric nature, which may be why she became a bit of a bully herself as a way of getting back at the world. Now, she smugly insists that vampires are the superior lifeform, and gets her kicks by pranking and terrifying the other students, who have a superstitious fear of her. She seems to have a particular interest in you, so she may prove a thorn in your side.\n\nStill, you get hints that she likes you more than she lets on. She seems to quietly seethe with jealousy when she sees you hanging out with someone else too much, and will subject them to increased mischief as if to ward them off. And being kind to her, rather than judgemental, can make her smug condescension give way to shocked, flustered stammering. Maybe there's a way to break through to her softer side?" },
    { id: 'valorie', name: 'VALORIE', cost: 'Costs -5 FP', birthplace: 'The Unterseeisch', signature: 'Aquatic Force', otherPowers: 'Psychic Force I, Forcefield, Sonic Boom, Plasma Strike, Energy Channel', imageSrc: 'https://i.ibb.co/xK7kwN0G/c7.jpg', description: "Rare for someone boastful to be able to back up their words, but Valorie did so with style when she slayed that Leviathan single-handedly, making her the youngest mage this millennium to solo a Grimsayer-tier Allmillor! She's quite prideful and playfully braggadocious, but not in the all-too-common way that drags other people down; instead, she strives to build her friends up, and is the first to sing their praises if they match or surpass her achievements. Her self-confidence and constant compliments often rubs off on friends with low self-esteem, making them feel much better about themselves.\n\nShe's the preeminent girly girl, enamored by fashion, makeup, shopping, and all the usual suspects. If you ever need a fashionista to make you look fabulous, she'd be happy to help. Just note she may be a little {i}too{/i} preoccupied with chasing trends. She's very relaxed most of the time, but insulting her friends earns her wrath!" },
    { id: 'stella', name: 'STELLA', cost: 'Costs -4 FP', birthplace: 'The Unterseeisch', signature: 'Smarts +', otherPowers: 'Ice Cold II, Aquatic Force, Energy Channel, Venture Capitalist, Tinkerer, Weaponsmith', imageSrc: 'https://i.ibb.co/Nb2jwhF/c8.jpg', description: "Stella's mother could frankly be called a nag, but generously be called a perfectionist. And perfect her she did. Average grades of 98, could play several instruments and three sports by 5, ran her own small company by 8... and all at the cost of a normal childhood. The upside to this is that she usually does things perfectly, and is thus happy as a clam. The downside is that if almost anything she's doing is even slightly {i}imperfect{/i}, she becomes overwhelmed with anxiety!\n\nShe still works basically 24/7 — leisure is a foreign concept to her — yet she somehow still finds the time to do nice things for her friends to make their lives easier. She projects an aura of prim and proper, and is fastidiously organized, dedicating every moment to self-improvement. She's a perfect study buddy or companion, but can seem like an uninterested friend, for she simply gets stressed out when not busy! It will take time to get her to be able to just hang out." },
    { id: 'bianca', name: 'BIANCA', cost: 'Costs -3 FP', birthplace: 'The Unterseeisch', signature: 'Superpowered Mind', otherPowers: 'Sensory Master, Energy Channel', imageSrc: 'https://i.ibb.co/tpSc7n6b/c9.jpg', description: "She grew up until now as a lighthouse operator with her father... and became just as drab as her old man, I must say. Can you imagine sitting around on an empty island staring at the sea for a decade? I'd go mad! But it accustomed her to a very slow and quiet lifestyle, so she really struggles to keep up with the hustle and bustle of school life. Smart as a whip, though. That observant, analytical mind of hers just notices things nobody else does... and while she rarely opens her mouth, whenever she does, her words are full of wisdom beyond her years.\n\nShe really likes spending time with her friends, but isn't one for conversation. Reading books together, watching the birds... that's what some people consider a good time, I guess. Waste of potential, though! With that brain, she could be the world's best tactician. Will you inspire her to abandon her placid ways and become a badass action girl? Or is there merit to a quiet life?" },
    { id: 'estrella', name: 'ESTRELLA', cost: 'Costs -4 FP', birthplace: 'Valsereth', signature: 'Speed +', otherPowers: 'Psychic Force I, Quick Twitch, Energy Channel, Sonic Boom', imageSrc: 'https://i.ibb.co/8LYbXgBM/c10.jpg', description: "Her one dream was to become a professional Segalanya racer, and she made great strides... until she hideously embarrassed herself while demonstrating her skills to an industry bigwig. No matter what, you can't seem to get any details about what actually happened — people just make vague allusions to the 'gryphon incident' while giggling to each other. Whatever happened, it convinced her her dreams were dashed forever, and she's gotten all youthfully mopey and melodramatic about it.\n\nEver-so-pragmatic, she's the ideal voice of reason — useful, considering how 'eccentric' the other classmates are — but she can oft straddle the line between realism and downright cynicism. Still, she's happy to give you a shoulder to cry on and a caution against your more ill-advised ideas. She helps others through their issues, but always keeps her own struggles bottled up inside, even with her closest friends." },
    { id: 'siouxsie', name: 'SIOUXSIE', cost: 'Costs -5 FP', birthplace: 'Valsereth', signature: 'Pyromaniac III', otherPowers: 'Thermal Weaponry, Plasma Strike, Strength +, Phase Shift, Rubber Physiology', imageSrc: 'https://i.ibb.co/hF3vVsCN/c11.jpg', description: "Describing herself as a missionary from the mysterious \"ninth Dominion\" beneath Mount Bearsmark, Siouxsie is ever-too-eager to preach the perfection of her fiery god Obium. She's quite a happy-go-lucky girl, even in cases where it's extremely inappropriate to be so — it's quite unnerving to watch her prance about so cheerfully all while searing the flesh from her enemies. She considers flames to be a blessing, not something to be feared, so we had to teach her that she can't just set everything on fire.\n\nShe loves destruction and is always yearning for a chance to wreak havoc, especially upon those who dare wrong her friends. She recognizes she's a fish out of water on the surface world, so she'll stick close to you and obediently follow all of your advice, thinking you an expert. She's pretty trusting and gullible, so you can convince her of some wacky things if you so choose. Once you have her loyalty, it will never waver." },
    { id: 'chandra', name: 'CHANDRA', cost: 'Costs -5 FP', birthplace: 'Valsereth', signature: 'Self Duplication', otherPowers: 'Phase Shift, Internal Manipulation, Supersize Me, Sensory Master, Energy Channel, Personification', imageSrc: 'https://i.ibb.co/zVp39dGt/c12.jpg', description: "Raised by a clan of famous treasure hunters, and already following in their footsteps, well-known for having acquired a staggering amount of valuable enchanted artifacts despite her young age. Smart and talented enough to coast by with modest passing grades for near-zero effort, as she believes the best way to learn is to get first-hand experience, and likes to skip classes to sniff out treasures and quests — half of which lead her to glory, and the other half leading her to a thorough scolding from the headmaster after she gets herself into trouble yet again.\n\nWhile she's incredibly reckless and blasé about her own safety, she's oddly cautiously when it comes to yours. She'll lose her mind if it ever seems like you've been hurt, and you'll get the biggest tearful hug once it turns out you're okay. She's the kind to surreptitiously tick treasures where her friends will 'discover' them, just to see their smiles. VERY competitive with her rivals." },
    { id: 'illuse', name: 'ILLUSE', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Spectral Form', otherPowers: 'Life Drain, Psychic Vampire, Spirit Medium, Fata Morgana Curse, Thoughtseer, Lucid Dreamer, Memory Lane', imageSrc: 'https://i.ibb.co/sv6z0RJZ/c13.jpg', description: "Dismissed as a mere urban legend by most students, Illuse seems to be the spirit of a slain mage reborn into a physical body with the intent of being added to the harem of a quite cruel necromancer — who, instead, died herself under very mysterious circumstances. Illuse is a mysterious girl who rarely likes to be seen by strangers, usually acting as an invisible poltergeist, or sometimes appearing in people's dreams. Playful and mischievous, snobs or bullies around campus are often subject to pranks by some unseen force few will believe exists.\n\nIf she likes you, she's clingy but quite shy, following you around and invisibly making your life easier. Expect to find all your chores done while you were out, or to wake up to breakfast in bed, or to hear of your foes tormented by a clever trickster. However, she'll need gradually encouragement and coaxing to be willing to actually reveal herself to you more and more." },
    { id: 'xena', name: 'XENA', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Thermal Weaponry', otherPowers: 'Ice Cold III, Speed +, Aquatic Force, Energy Channel', imageSrc: 'https://i.ibb.co/pvB1B3wY/c14.png', description: "This one's a real stoic, always as cool as that sword she swings around. That's how everyone was up in Ialedo — simple, honest folk. She was raised a Knight of Snowholme, dedicated to protecting the whole region... but there was nothing they could do once three grimsayers showed up. I have to imagine she's upset, deep down, after watching her home be wiped away.\n\nShe's deadpan and gets straight to the point, which makes many people think she just has a dry sense of humor, so she gets confused when people start laughing at what she considered a serious remark. She also takes everything pretty literally, so don't expect her to understand metaphor or hyperbole. Still, her utter calmness in any situation tends to calm those around her, and she can be the voice of reason when her friends minds get clouded by emotion or panic. And you'll find she's not truly as emotionless as she appears, if you get her to open up to you." },
    { id: 'rosalind', name: 'ROSALIND', cost: 'Costs -3 FP', birthplace: 'Gohwood', signature: 'Breaker of Minds', otherPowers: 'Crowd Control, Material Transmutation', imageSrc: 'https://i.ibb.co/CpWrfqRq/c15.png', description: "The royal magus lineages of Gohwood don't participate in the same foster program as regular mages, so we can't vet the sort of families they go into. This can lead to some... questionable parenting. Poor Rosalind here is the type of girl used to having an army of servants, and is struggling to come to grips with the fact the real world isn't quite like life at the Mayleaf Palace. She's set to inherit the entire ancient Gohwood monarchy, after all! So she can come off as a little bossy and prissy, I must admit.\n\nI'd say you should knock her ego down a peg, but... I feel a more gentle approach might work just as well, honestly. I can't even imagine the pressure she must be under... and have you heard the way her parents scream at her when she so much as curtsies the wrong way? She could use a friend who can bring her down to Earth and show her more to life. If you can win her over, you'll have a future queen on your side!" },
    { id: 'ruby', name: 'RUBY', cost: 'Costs -4 FP', birthplace: 'New Palisade', signature: 'Heavily Armed', otherPowers: 'Nanite Armor II, Manual Override, CH402.NP5, Domain Master I, Weapon Sabotage, Metal Skin, Grey Goo, Strength +, Incredible Will', imageSrc: 'https://i.ibb.co/j9qYhKLQ/c16.jpg', description: "Sporty and utterly competitive, Ruby hopes to become the absolute best at everything she does. She's one of the top Mazball players at her age level, even though she often gets into trouble due to her frequent showboating and overestimating her own abilities. She designed that massive fist she can juggle up, and can send her enemies flying across the entire field!\n\nIf you two can find a shared interest, she's the perfect friendly rival — both of you pushing eachother to work harder and get better and better. With others, though, she can have a short temper, especially if she keeps getting trounced by a better opponent. She can train basically non-stop for months trying to overtake them! It's pretty... obsessive. She looks down on laziness and will always try to help you break out of your comfort zones and pursue your goals. She oft speaks before she thinks, though, so she can accidentally come off as a bit rude." },
    { id: 'cordelia', name: 'CORDELIA', cost: 'Costs -3 FP', birthplace: 'New Palisade', signature: 'Psychic Surgery', otherPowers: 'Flashback, Charisma +, Healing Bliss, Defensive Circle, Guardian Angel, Rejuvenating Bolt', imageSrc: 'https://i.ibb.co/mPQg27B/c17.jpg', description: "This one scares me a tiny bit! She tests highly for antisocial personality disorder... in other words, a sociopath, meaning she can't feel empathy for others. That doesn't mean she's {i}evil!{/i} Just a bit... troubled. She is a brilliant surgeon, though, especially given her young age. If you're injured, she's very enthusiastic about cutting you open and fixing what's wrong. Maybe too enthusiastic.\n\nAround most people, she fakes a very polite, demure personality. It's chillingly convincing. Her real self is quite, well, cynical, with a dry wit and a pitch black sense of humor. She's not afraid to speak her mind and take the piss out of things others consider sacred, which may be useful if you want a friend who can offer very frank critique. If you're dim-witted, you'll only annoy her, but if you're bright enough to earn her respect, she's incredibly loyal. She's, ahem, trying her best to stay on the straight and narrow... but she could definitely use a positive influence!" },
    { id: 'anna', name: 'ANNA', cost: 'Costs -3 FP', birthplace: 'New Palisade', signature: '?????', otherPowers: 'Forcefield, Energy Channel, Sonic Boom', imageSrc: 'https://i.ibb.co/SDpwhdbK/c18.png', description: "Anna is no typical mage, but a Distortion — her power comes not from the Mother, but from a glitch in reality. Namely, anything she truly believes in becomes real. This may sound easy to take advantage of, but she's immune to psychic manipulation, and her strange psychology makes her impossible to intentionally fool. Trust me, a team of rather unscrupulous scientists tried their best, and they were rewarded for their efforts only by getting slaughtered by Anna's rather disturbing \"imaginary friend\", Mr. Muggins.\n\nNow fostered by the state, Anna is the 'weird kid' in school, usually off in her own little world. When conversed with, she's super excitable, bubbly and affectionate, yet basically impossible to understand. She prefers to express herself by making paintings and giving hugs and gifts — the universal languages. She has no friends, so if you're nice to her, she'd be ecstatic! And her power can be useful in unpredictable ways." },
    { id: 'stacy', name: 'STACY', cost: 'Costs -4 FP', birthplace: 'The Rovines', signature: 'Weaponsmith', otherPowers: 'Master Mechanic I, Tinkerer, Kaboom!, Max Security, Nanite Armor I', imageSrc: 'https://i.ibb.co/6RtQ9kFQ/c19.png', description: "Pffft, oh my gosh. She's so adorable walking around with a 20mm rifle the same size as her. She'll grow into it, I'm sure. Her mom was a hardcore prepper, one of those types who think reality will collapse in a century, so Stacy has been undergoing brutal military training since she was a toddler. School has finally afforded her an opportunity to escape, but she struggles fitting in. She can tell you {i}everything{/i} about IEDs or weapon calibers, but knows nothing about buying clothes or doing schoolwork or even just how to interact with her fellow mages.\n\nShy and awkward, she's used to a heavily regimented life and has trouble making her own decisions. A quiet part of her fantasizes about what it's like to be a more typically girly girl and get to wear cute dresses. She'll be immensely grateful to you if you help her break out of her comfort zone. And if you like guns, she'd be more than happy to gush about them for hours." },
    { id: 'meryll', name: 'MERYALL', cost: 'Costs -4 FP', birthplace: 'The Rovines', signature: 'Beastmaster', otherPowers: "Mage's Familiar III, Sustaining Bond, Healing Bliss, Rejuvenating Bolt, Defensive Circle", imageSrc: 'https://i.ibb.co/BKf1nC3h/c20.jpg', description: "The school keeps getting noise complaints about her dorm room — it's like an entire zoo in there! She's got everything from fluttering little fairies, to three-headed snakes, to a kappa of all things, although she seems most attached to a big poison-spitting manticore named Jandi. Chief beastmaster of Castle Borthrough, she explored all over and met nearly every kind of beast, but there's a few rare species she's still looking for.\n\nShe has extensively studied healing magic in order to play veterinarian for her pets, and help her friends as well. She's quite the serious sort, with only her pets (and you) bringing a smile to her face, and a bit hard-headed about her ideals, which encompass anything from honor, helping those in need, and respecting animals. She's got a real righteous fury and a desire to see wrongdoers brought to justice. However, she is not cruel, and prefers to see people change their ways rather than having to battle them." },
    { id: 'zorreth', name: 'ZORRETH', cost: 'Costs -3 FP', birthplace: 'The Rovines', signature: 'Shed Humanity II', otherPowers: 'Pyromaniac II, Plasma Strike, Sonic Boom, Strength +, Speed +', imageSrc: 'https://i.ibb.co/SD8Kj6sm/c21.jpg', description: "She disappeared off the grid long ago, and was presumed dead. Then, we found out her parents were actually messily devoured after picking a fight with a pair of dragons, who proceeded to adopt \"Zorreth\". The school managed to work out a deal with them to let her come here, but she's a bit of a handful. She considers herself a dragon and far above mankind, and is easy to anger, transforming into her 3 story tall draconic form and causing a huge mess. She can be placated with shiny things to add to her 'hoard', which can be as simple as a marble or a button.\n\nIf she likes you, she'll decide you're \"one of the good humans\" and treat you like a treasured pet. She'll ferociously defend you against all who would harm you, but can be quite possessive. Maybe you can help her learn to fit in better? Just, whatever you do, {i}don't{/i} hurt her. Her mom's an {i}actual{/i} dragon, and one so massive she makes Zorreth's draconic form look tiny by comparison." },
    { id: 'ayuzawa', name: 'AYUZAWA', cost: 'Costs -5 FP', birthplace: 'Jipangu', signature: "Oni's Blessing", otherPowers: 'Strength +, Charisma +, Quick Twitch, Weaponsmith, Energy Channel, Defensive Circle, Phase Shift', imageSrc: 'https://i.ibb.co/gbcpH1vn/c22.jpg', description: "Oni are extremely rare and benevolent yokai that rarely choose a lucky newborn mage to fuse with, offering them immense powers in return for enlisting them in the onis' eternal war against all other sorts of yokai. Not that Ayuzawa, being the goody-two-shoes hero type she is, needed any prodding to dedicate herself to defending her beloved school against its spiritual assailants. President of the student council and a few other clubs, and prospective valedictorian of her class, no one has as much school spirit as she does!\n\nGiven her track record, she'll probably act like a supportive big sister, giving you advice, making sure you're safe and even packing your lunches. You're going to have to set some boundaries if you don't want her babying you. Eminently responsible, almost overly so, she'd rather die than be late to a scheduled meeting. Idealistic, she tends to assume the best of everybody, at the risk of becoming easy to take advantage of." },
    { id: 'momoi', name: 'MOMOI', cost: 'Costs -5 FP', birthplace: 'Jipangu', signature: 'Master Telepath', otherPowers: "Cursemaker's Cookbook, Shed Humanity I, Psychic Force I, Chloromancy, Thoughtseer, Lucid Dreamer", imageSrc: 'https://i.ibb.co/GQj3z2cS/c23.jpg', description: "She's taken full advantage of Jipangu reverence for mages, living in her massive shrine in the woods and calling herself the Goddess of the Hachimori — sitting on a bean bag throne and being hand-fed snacks by her dutiful supplicants, the whole shebang. Smug and playful, it seems she has decided you are the heir to the title of 'Protector of the Goddess', and will set up devious little challenges to test whether you are yet worthy to be her 'right-hand mage'.\n\nHailing from a looong line of kitsunes, the protection of nature is always her top priority, and defiling her forest is a quick way to spur her to fury. She transforms into a large, white-furred, nine-tailed fox when fighting off intruders. Her followers have to spend a half hour just grooming her tails every day. She gets very grumpy and pouty when someone denies her divinity. She likes spending quiet foggy mornings together in the woods drinking sencha tea." },
    { id: 'licenda', name: 'LICENDA', cost: 'Costs -3 FP', birthplace: 'Jipangu', signature: 'Flowers of Blood', otherPowers: 'Life Drain, Spirit Medium, Spectral Form', imageSrc: 'https://i.ibb.co/LDQjngdm/c24.png', description: "I must strongly caution you on this one. Poor Licenda here is as broken as a person can be, a complete shell of her former self, barely ever even speaking. Years ago, she emerged the only surviving kidnapping victim of a deranged sexual cult of sadists and hedonists, egging each other on to be ever more \"creative\" in their tortures. The things they {i}did{/i} to her were expunged from all records, and most who've heard the details opted for a memory wipe rather than live with that terrible knowledge. She still isn't allowed to die, even. Outside of the Sinthru covens, these sorts of things have {i}never{/i} happened since the Forsaken Age, thousands of years ago! Perhaps our reality really is devolving...\n\nIt seems she's still followed by the ghost of her past - literally. Most spirits are easily dispatched, but this one is completely unprecedented in its power and violent nature. There's technically no evidence of any connection, but... I feel I must warn you a few people who've hung around Licenda have disappeared under mysterious circumstances. Some rumor that the spirit is her own sister, whose life she was forced to snuff out for the viewing pleasure of their captors. I don't even remember what her name was." }
];

export const CUSTOM_CLASSMATE_CHOICES_DATA: CustomClassmateOption[] = [
    { id: 'custom_classmate_25', cost: 'Costs -4 FP', description: 'Create a companion with 25 Companion Points.' },
    { id: 'custom_classmate_35', cost: 'Costs -6 FP', description: 'Create a companion with 35 Companion Points.' },
    { id: 'custom_classmate_50', cost: 'Costs -8 FP', description: 'Create a companion with 50 Companion Points.' },
];
