
import type { ClosedCircuitsSigil, ClosedCircuitsPower } from '../../types';

// Closed Circuits
export const MARGRA_DATA = {
    title: "MARGRA, DAUGHTER OF UNITY",
    imageSrc: "/images/LDwmm3Br-main1.jpg",
    description: `The youngest of the Daughters, born only millennia ago. People forget this, but back in the time of the original Sinjade Doctrine, mages were bestowed basically unlimited power. Obviously, this could not last long. To prevent an uprising, in the Sinthru Covenant, the Mother offered these mages immense influence over the world's politics via voting in the newly established Red-Jade Council, and Margra was birthed to serve as their intermediary. Some say the Red-Jade Council is a glorified social club; a bunch of bored old corporate CEOs getting together to play bingo and gossip like schoolgirls. Others say they're the true power behind the throne, cementing their influence through artificial scarcity and pulling all the strings while the Mother slowly devolves into a ceremonial figurehead. ({i}I will say, if that last one were true, Mother would probably be quite pleased with the arrangement, in my opinion. She never was one for geopolitics...{/i})

Her spells are probably the most rarely studied of all of them, for they're far less straightforward and generally require more significant amounts of thought and creativity put into how they can be used — you won't find any good old projectile spells in her arsenal! However, if you put in the legwork and are the clever sort, you'll find that the blessings she offers are often the best a mage could hope for. In fact, she offers far more {r}Xuth{/r}-level spells than any of the other daughters! Just know you may be vulnerable if the direct combat-oriented mages catch you off your guard.`
};

export const CLOSED_CIRCUITS_DATA = {
    title: "THE BLESSING OF CLOSED CIRCUITS",
    imageSrc: "/images/SwdQ7cVY-main2.jpg",
    description: `Okay, to clear things up: magitech is the art of creating semi-magical technology, while technomancy is the art of controlling existing technology connected to the Web. The Web could be thought of as a verse of its own, layered over and connected to our reality. If you want to start cracking systems, you'll have to {w}make a{/w} {w}Net Avatar{/w}, which is sort of like an additional, digital alter ego. Of course, corporations and stuff don't really want you cracking their databases open, so expect firewalls, spiderbots, and other defenses! Destroyed net avatars take a month to be recreated.

Another bonus: a few decades ago, Laser Focus Inc. accidentally leaked a bunch of experimental self-replicating nanites, and by now they've proliferated the entire atmosphere a trillion times over. They don't really do much by themselves, but they're super low security, so technomancer have found they can easily make 'em do a whole bunch of things!`
};

export const CLOSED_CIRCUITS_SIGIL_TREE_DATA: ClosedCircuitsSigil[] = [
    { id: 'script_kiddy', title: 'SCRIPT KIDDY', description: '', imageSrc: '/images/SFbsP2R-juathas.png', prerequisites: [], benefits: { netAvatar: 1 } },
    { id: 'kyrotik_armor', title: 'KYROTIK ARMOR™', description: 'Get all suited up!\nUnlocks Nanite Armor I', imageSrc: '/images/DD9xYmP9-lekolu.png', prerequisites: ['script_kiddy'], unlocks: ['nanite_armor_i'], benefits: { naniteControl: 2 } },
    { id: 'heavy_duty', title: 'HEAVY DUTY', description: 'Unlocks Nanite Armor II', imageSrc: '/images/Dg6nz0R1-purth.png', prerequisites: ['kyrotik_armor'], unlocks: ['nanite_armor_ii'], benefits: { naniteControl: 2 } },
    { id: 'ez_hack', title: 'EZ-HACK™', description: "With our software, you'll be a pro hacker in no time!", imageSrc: '/images/DD9xYmP9-lekolu.png', prerequisites: ['script_kiddy'], benefits: { technomancy: 1 } },
    { id: 'hacker_i', title: 'HACKER I', description: '', imageSrc: '/images/zTm8fcLb-kaarn.png', prerequisites: ['ez_hack'], benefits: { technomancy: 1 } },
    { id: 'nanite_master', title: 'NANITE MASTER', description: 'Unlocks Nanite Armor III', imageSrc: '/images/rfs5FtF3-xuth.png', prerequisites: ['heavy_duty'], unlocks: ['nanite_armor_iii'], benefits: { naniteControl: 1 } },
    { id: 'black_hat', title: 'BLACK HAT', description: 'Unlocks 9R1M01R3.RPM', imageSrc: '/images/nq80Y3pk-sinthru.png', prerequisites: ['hacker_2'], unlocks: ['9r1m01r3_rpm'], benefits: { technomancy: 1 } },
    { id: 'hacker_2', title: 'HACKER 2', description: '', imageSrc: '/images/zTm8fcLb-kaarn.png', prerequisites: ['hacker_i'], benefits: { technomancy: 1 } },
    { id: 'l33t_h4xx0r', title: 'L33T H4XXOR', description: 'Unlocks Manual Override', imageSrc: '/images/Dg6nz0R1-purth.png', prerequisites: ['hacker_2'], unlocks: ['manual_override'], benefits: { technomancy: 2 } },
];

export const NET_AVATAR_DATA: ClosedCircuitsPower[] = [
    { id: 'f41th_jhc', title: 'F41TH.JHC', imageSrc: '/images/xKGt7pKD-a1.jpg', description: "For you, the Web is a stereotypical void of data and network nodes, and you look much like yourself. You're a jack-of-all-trades with the ability to create powerful viruses to sabotage specific parts of a system, ranging from detection to defense, giving you a lot of flexibility in your approach.", grade: 'kaarn' },
    { id: 'ch402_mp5', title: 'CH402.MP5', imageSrc: '/images/D3mF73p-a2.png', description: "For you, the Web is a bitter scarlet battleground, and you a scarred general. You have no interest in stealth; you are like a walking DDOS, and every system is sent into panic by your approach as they're flooded with junk data. You bring security systems to their knees through sheer brute force.", grade: 'kaarn' },
    { id: 'n05t4lg14_fmj', title: 'N05T4LG14.FMJ', imageSrc: '/images/3Kk4szK-a3.jpg', description: "For you, the Web is a maze of places from old memories viewed through a haze of VHS static, and you an innocent child. You're small, clever, and move silently, and are easily underestimated and overlooked as you sneak through their labyrinthian databases. They'll never even know you were there.", grade: 'kaarn' },
    { id: '9r1m01r3_rpm', title: '9R1M01R3.RPM', imageSrc: '/images/nMX1VrSL-a4.jpg', description: "{i}Requires {bp}Black Hat.{/bp}{/i} To you, the Web is just a bunch of junk you brushed aside to get to your goals, and you don't bother fighting fair. The coven has shown you backdoors hardcoded into most technology. You've also gained a botnet — compromised avatars who can do all your dirty work for you.", requires: ['black_hat'], grade: 'sinthru' },
];

export const TECHNOMANCY_DATA: ClosedCircuitsPower[] = [
    { id: 'domain_master_i', title: 'DOMAIN MASTER I', imageSrc: '/images/JF7DTbMf-a5.jpg', description: "You can exert influence over any many types of simpler mundane devices around you. Instantly change displays, disable security systems, unlock electric doors, empty vending machines and ATMs, disable phones, and all sorts of other things. Much harder to sabotage high-level security devices.", grade: 'kaarn' },
    { id: 'weapon_sabotage', title: 'WEAPON SABOTAGE', imageSrc: '/images/RTxcKHj0-a6.jpg', description: "Sabotage enemy weaponry during battle! The difficulty of this depends on how many Weapon Points have been invested in said weapon. At worst, you may just cause it to shoot slightly slower or do slightly less damage; at best, you might cause it to jam up or even explode in the users hands!", grade: 'kaarn' },
    { id: 'digital_infiltrator', title: 'DIGITAL INFILTRATOR', imageSrc: '/images/zhYYCKxZ-a7.png', description: "These people really think their flimsy passwords are going to protect them? You're an expert at cracking computers, servers, databases, and hacking people's accounts and even entire websites. New security measures are being released every single day, though, so try to keep up with the arms race.", grade: 'kaarn' },
    { id: 'manual_override', title: 'MANUAL OVERRIDE', imageSrc: '/images/PZ30Dhcz-a8.jpg', description: "{i}Requires {g}L33T H4XXOR.{/g}{/i} Instead of merely being able to sabotage things, your other powers can now take control of them. Turn security turrets against their own controllers, take remote control of mechs, vehicles, and enemy's weapons, and control every single byte of computers and phones.", requires: ['l33t_h4xx0r'], grade: 'purth' },
    { id: 'domain_master_ii', title: 'DOMAIN MASTER II', imageSrc: '/images/fzSgSGCg-a9.png', description: "{i}Requires {w}Domain Master I.{/w}{/i} You're now more capable of taking on military-grade security devices. Disable security cameras and turrets, easily slip through sealed entrances and laser-grid security systems, and duck through facilities without setting off a single alarm.", requires: ['domain_master_i'], grade: 'kaarn' },
    { id: 'vehicle_sabotage', title: 'VEHICLE SABOTAGE', imageSrc: '/images/Fb2tFR8J-a10.jpg', description: "Same as above. The more {i}Vehicle Points{/i} invested in a vehicle, the more difficult it is to sabotage. At worst, you can make it flash a few error screens and be a bit more difficult to control and drive; at best, you'll be able to suddenly shut off all steering, or cause internal damage that'll have to be repaired.", grade: 'kaarn' },
    { id: 'counter_hacker', title: 'COUNTER HACKER', imageSrc: '/images/wZwL5LsV-a11.jpg', description: "You're an expert at combat with other Avatars in the web, overloading their systems until they disappear completely. This is used either to defeat other hackers attempting to infiltrate your device, or to take down guard avatars who are personally defending systems you're trying to sabotage.", grade: 'kaarn' },
    { id: 'verse_hijack', title: 'VERSE HIJACK', imageSrc: '/images/VcTqTNRp-a12.jpg', description: "{i}Requires {bp}9R1M01R3.RPM.{/bp}{/i} You now have a backdoor into Nero Inc.'s software! You can attack verses in various ways, from uploading malware, causing natural disasters, shrinking their spread or area of effect, etc. However, they'll know the general area the attacks are coming from.", requires: ['9r1m01r3_rpm'], grade: 'sinthru' },
];

export const NANITE_CONTROL_DATA: ClosedCircuitsPower[] = [
    { id: 'heavily_armed', title: 'HEAVILY ARMED', imageSrc: '/images/HLP0j1R8-a13.jpg', description: "Instead of holding your weapon in your hand, you can call upon any nanites in the area to conjoin in the shape of your weapon around one of your limbs, turning said limb into a cannon, sword, hammer, power fist, or what have you. Design it with {w}30 Weapon Points{/w} on the {i}Reference Page{/i}.", grade: 'kaarn' },
    { id: 'nanite_armor_i', title: 'NANITE ARMOR I', imageSrc: '/images/svKCdq1T-a14.jpg', description: "{i}Requires {y}Kyrotik Armor™.{/y}{/i} We here at Kyrotik vow to keep our customers safe so they may live another day and buy more products! To this end, with as little as a snap of your fingers, nanites will arrange themselves in the shape of a comfy bodysuit that massively boosts durability!", requires: ['kyrotik_armor'], grade: 'lekolu' },
    { id: 'nanite_armor_ii', title: 'NANITE ARMOR II', imageSrc: '/images/mrW6KLr8-a15.jpg', description: "{i}Requires {y}Nanite Armor I{/y} and {g}Heavy Duty.{/g}{/i} A bit less comfortable, but fitting for those who want maximum protection! Your armor now has extra thick reinforced plates around certain vital areas that are nearly impenetrable by almost all attacks. They don't offer nearly 100% coverage, though.", requires: ['nanite_armor_i', 'heavy_duty'], grade: 'purth' },
    { id: 'nanite_armor_iii', title: 'NANITE ARMOR III', imageSrc: '/images/HL5CpngK-a16.jpg', description: "{i}Requires {g}Nanite Armor II{/g} and {r}Nanite Master.{/r}{/i} Takes the form of an extremely comfortable thin bodysuit, almost like a second skin. However, the kinetic energy of attacks directed at it simply ceases to exist, in flagrant disregard for the first law of thermodynamics. If a bullet is fired, it will suddenly lose all momentum an instant before hitting its target; even a tank shell will clatter to the ground without the wearer even feeling it. Thermal energy is also controlled, creating a pocket of safe and comfortable air around its wearer. Its offers immense defensive capabilities despite being so thin. It can also be made to change color and appearance instantly according to the wearer's whims; if they wish, it can even be made to resemble normal clothes. However, there will always be at least a few 'weak points' in the armor that a knowledgeable opponent can exploit; failing this, attacks that encompass the victim completely are second best in terms of effectiveness. In one case, after being subject to a nuclear blast at point-blank range, the wearer was completely disintegrated, but the suit was later recovered without so much as a single scratch.", requires: ['nanite_armor_ii', 'nanite_master'], grade: 'xuth' },
    { id: 'metal_skin', title: 'METAL SKIN', imageSrc: '/images/4Z0WFgjN-a17.png', description: "When your skin is penetrated, nanites will fill the wound and solidify, essentially patching it up and staunching any bleeding. As natural healing processes kick in, these patches will be replaced by healthy bodily cells, but in the meantime, they prevent blood loss or your wounds getting worse.", grade: 'kaarn' },
    { id: 'nanite_form', title: 'NANITE FORM', imageSrc: '/images/QvztGcdK-a18.png', description: "You can trigger a couple minutes-long transformation in which nanites reconfigure your entire body into a robotic form. Design this form with {w}40 Beast Points{/w} on the {i}Reference Page{/i}, but the default category must be {w}Humanoid{/w} and you cannot select options marked with *.", grade: 'kaarn' },
    { id: 'grey_goo', title: 'GREY GOO', imageSrc: '/images/QjMHmKt0-a19.jpg', description: "Just by concentrating on a nearby foe, you can have nearby nanites pick them apart molecularly. Near-instant death for mundanes, but mages are too durable to be affected beyond some pain. If they are already cut, however, those wounds will slowly be eaten away at and get larger and worse.", grade: 'kaarn' },
];
