
import type { CompellingWillSigil, CompellingWillPower } from '../../types';

export const ARABELLA_DATA = {
    title: "ARABELLA, DAUGHTER OF HOPE",
    imageSrc: "https://i.ibb.co/V0242j3P/main5.jpg",
    description: `The middle child of the family, and perhaps the most famous, or at least uncontroversial. She's appeared at various times throughout history to save all mankind whenever it needed her most, most notably leading Gohwood's Holy Knights during the war, so she's beloved by all but the most cynical souls and has become the {i}de facto{/i} mascot of mages in general. Believe me when I say Jipangu has made a {i}ton{/i} of cartoons about her. Unfortunately, I fear that deep down, Arabella has come to despise her own fame. I can always sense that she wishes she could just be a normal girl, and not have to spend eternity locked away in her gilded palace in Eden. The Mother reminds her that she serves the people best as a symbol; a beacon of hope, a watchful protector, a role model for them all to aspire to. Still... I've heard whispers she lets her moonlight disguised as a normal mage and go on adventures down on Earth, from time to time. Keep an eye out, and maybe, you just might meet her...
    
Her blessings are so straight-forward and pragmatic that many mages don't really bother to study anything beyond them. Stuff like throwing fireballs, conjuring familiars, brewing potions... you know, all the things that immediately spring to mind when you think 'magic'. Some hipsters laugh at this brand of magic for being 'boring' and 'soulless', but I think, deep down, they must regret having passed over such useful, fundamental spells...`
};

export const COMPELLING_WILL_DATA = {
    title: "THE BLESSING OF COMPELLING WILL",
    imageSrc: "https://i.ibb.co/VhFNX8k/main6.jpg",
    description: `The second most basic Blessing by my estimation, this encompasses much of the direct means of dealing damage at a range, from fireballs to energy beams to just smacking things with your targets. While other may be of other more creative means of attacking that are as effective, having some tried-and-true basic attacks to fall back on can mean the difference between life and death in a pinch. Essentially, this Blessing encompasses the incredibly broad concept of 'mental manipulation of energy' -- a.k.a. telekinesis. This is useful even in regular day-to-day life: it's like having a dozen extra pairs of hands! Plus, once you start manipulating things on the atomic level, you can get very creative...
    
Explaining its historical significance would be difficult since this Blessing was used extensively in every conflict. A poll performed by Cauldron Magazine indicated that over 38% of mages specialize in this Blessing primarily.`
};

export const COMPELLING_WILL_SIGIL_TREE_DATA: CompellingWillSigil[] = [
    { id: 'manipulator', title: 'MANIPULATOR', description: '', imageSrc: 'https://i.ibb.co/SFbsP2R/juathas.png', prerequisites: [], benefits: { telekinetics: 1, metathermics: 1 } },
    { id: 'telekinetic_i', title: 'TELEKINETIC I', description: '', imageSrc: 'https://i.ibb.co/zTm8fcLb/kaarn.png', prerequisites: ['manipulator'], benefits: { telekinetics: 1 } },
    { id: 'thermal_master', title: 'THERMAL MASTER', description: 'Unlocks Pyromaniac III and Ice Cold III', imageSrc: 'https://i.ibb.co/Dg6nz0R1/purth.png', prerequisites: ['manipulator'], benefits: { metathermics: 2 }, unlocks: ['pyromaniac_iii', 'ice_cold_iii'] },
    { id: 'psycho', title: 'PSYCHO', description: '', imageSrc: 'https://i.ibb.co/Dg6nz0R1/purth.png', prerequisites: ['telekinetic_i', 'thermal_master'], benefits: { telekinetics: 1, metathermics: 1 } },
    { id: 'thermosword', title: 'THERMOSWORD™', description: 'Unlocks Thermal Weaponry', imageSrc: 'https://i.ibb.co/DD9xYmP9/lekolu.png', prerequisites: ['telekinetic_i', 'thermal_master'], benefits: { metathermics: 1 }, unlocks: ['thermal_weaponry'] },
    { id: 'telekinetic_ii', title: 'TELEKINETIC II', description: '', imageSrc: 'https://i.ibb.co/zTm8fcLb/kaarn.png', prerequisites: ['psycho'], benefits: { telekinetics: 1 } },
    { id: 'reality_bender', title: 'REALITY BENDER', description: 'Unlocks Subatomic Manipulation', imageSrc: 'https://i.ibb.co/rfs5FtF3/xuth.png', prerequisites: ['telekinetic_ii'], benefits: { telekinetics: 1 }, unlocks: ['subatomic_manipulation'] },
];

export const TELEKINETICS_DATA: CompellingWillPower[] = [
    { id: 'psychic_force_i', title: 'PSYCHIC FORCE I', imageSrc: 'https://i.ibb.co/PZwsqvSr/t1.jpg', description: "You can telepathically exert incredible force on inorganic objects within a modest radius, enough to send a double-decker truck flying at a foe, or fire an armory's worth of guns at a foe simultaneously. The more mass you are affecting, the less precise you can be. Effect weakens with greater distance.", grade: 'kaarn' },
    { id: 'psychic_force_ii', title: 'PSYCHIC FORCE II', imageSrc: 'https://i.ibb.co/8gBhVJg7/t2.jpg', description: "{i}Requires {w}Psychic Force I.{/w}{/i} Your psychic influence and range is doubled, allowing you to bring buildings down or toss a train at your enemy. You can also effectively change the direction or intensity of gravity within a sizable area. With great effort, you can briefly affect your enemy directly.", requires: ['psychic_force_i'], grade: 'kaarn' },
    { id: 'forcefield', title: 'FORCEFIELD', imageSrc: 'https://i.ibb.co/TxM6PW00/t3.jpg', description: "You can create a small spherical field that deflects against even the most powerful kinetic attacks. However, it can get exhausting to deflect multiple attacks, so you can't expect to just stand there and let your forcefield soak up an entire barrage. Best to use it only briefly to block individual moves.", grade: 'kaarn' },
    { id: 'subatomic_manipulation', title: 'SUBATOMIC MANIPULATION', imageSrc: 'https://i.ibb.co/xK6ymNs9/t4.jpg', description: "{i}Requires {r}Reality Bender.{/r}{/i} Your telekinetic powers are now precise enough to affect change on a molecular level. Of course, one problem persists: you still can't actually perceive individual atoms, much less individually manipulate them. However, your power is 'smart' enough to understand your intentions if performing the following actions:\n- Reverse entropy and stabilize radioactive materials (or vice versa).\n- Manipulate photons within a few meters to create detailed visual illusions.\n- Gradually change the structure or materials of inorganic objects being touched or held, even to the point of slowly creating or destroying matter.\n- Violate the Pauli Exclusion Principle and allow solid objects to phase through each other. For example, you can walk through a wall, or cause someone to sink into the concrete ground beneath them as if it were quicksand.\n- After a short period of deep concentration on an area, can spontaneously create, and then split, fissile nuclides in order to induce a micro-nuclear explosion equivalent to around 0.1 kilotons of TNT maximum. Don't stand too close!", requires: ['reality_bender'], grade: 'xuth' },
    { id: 'energy_channel', title: 'ENERGY CHANNEL', imageSrc: 'https://i.ibb.co/39gVtQw0/t5.jpg', description: "This allows two abilities. First, you can throw basketball-sized glowing balls of energy from your hand at high speeds, which explode on impact. These aren't too powerful, but can be rapidly fired. The second is a high-powered, constant beam of energy. It's hard to hit, but devastating to its target.", grade: 'kaarn' },
    { id: 'aquatic_force', title: 'AQUATIC FORCE', imageSrc: 'https://i.ibb.co/27wvHSZq/t6.png', description: "You have a particular power over liquids. You can telekinetically move upwards of billions of gallons of water — enough to part the Red Sea, with enough effort! You can move smaller quantities at rapid speeds, sending bursts of water at foes with enough force to annihilate entire buildings.", grade: 'kaarn' },
    { id: 'sonic_boom', title: 'SONIC BOOM', imageSrc: 'https://i.ibb.co/gn9v6g1/t7.jpg', description: "After a few seconds' preparation, you can let out a massive burst of telekinetic force in all directions powerful enough to capsize a battleship and send a tank flying into the sky. Such power is released that it damages even yourself significantly, meaning it's best saved as a last-ditch attack or finisher.", grade: 'kaarn' },
];

export const METATHERMICS_DATA: CompellingWillPower[] = [
    { id: 'pyromaniac_i', title: 'PYROMANIAC I', imageSrc: 'https://i.ibb.co/whthGWtP/t8.jpg', description: "The most generic type of magic out there! Let waves of superheated air smash into your enemy, or billow out pillows of flame to surround them from all sides... or just throw a fireball. That works, too. Your fire is unnaturally hot but still doesn't do a ton of damage -- but it is very painful.", grade: 'kaarn' },
    { id: 'pyromaniac_ii', title: 'PYROMANIAC II', imageSrc: 'https://i.ibb.co/0yf69srk/t9.jpg', description: "{i}Requires {w}Pyromaniac I.{/w}{/i} Combatants will have to keep their distance, for your flames are always growing of course, but only are they stronger, but you can manipulate greater amounts of fire in more precise ways, and even superheat your own body to the point it's painful just to be near you.", requires: ['pyromaniac_i'], grade: 'kaarn' },
    { id: 'pyromaniac_iii', title: 'PYROMANIAC III', imageSrc: 'https://i.ibb.co/Ld8yvM4y/t10.jpg', description: "{i}Requires {w}Pyromaniac II{/w} and {g}Thermal Master.{/g}{/i} Your flames are now even stronger, and you're like walking sun in combat, to the point the bullets melt in midair before even making it close. Such is your might that you can you can fill the battlefield with walls of flame, or call down devastating firestorms.", requires: ['pyromaniac_ii', 'thermal_master'], grade: 'purth' },
    { id: 'ice_cold_i', title: 'ICE COLD I', imageSrc: 'https://i.ibb.co/S4FSZry2/t11.jpg', description: "You can turn the battlefield into a miserable tundra that can slow, but that still won't do much to the average foe beyond distracting them. More effective is forming massive chunks and spikes of ice and hurling them at your foes at high speeds, or causing them to just up from the ground.", grade: 'kaarn' },
    { id: 'ice_cold_ii', title: 'ICE COLD II', imageSrc: 'https://i.ibb.co/jPX2LPPY/t12.jpg', description: "{i}Requires {w}Ice Cold I.{/w}{/i} Not only is your ability to create and fire icy projectiles boosted tenfold, but you can now strike your opponent with gusts of super chilled air, partially freezing enemies and chipping away at their ability to fight. If they're weakened, you can freeze them in a block of ice!", requires: ['ice_cold_i'], grade: 'kaarn' },
    { id: 'ice_cold_iii', title: 'ICE COLD III', imageSrc: 'https://i.ibb.co/sJ6QSYB6/t13.jpg', description: "{i}Requires {w}Ice Cold II{/w} and {g}Thermal Master.{/g}{/i} Anything that so much as nears you in combat will freeze solid nearly instantly, and you can create massive structures out of ice to capture your foes or hurl an entire glacier at an unlucky foe. Your breath alone is so cold it almost nears absolute zero.", requires: ['ice_cold_ii', 'thermal_master'], grade: 'purth' },
    { id: 'plasma_strike', title: 'PLASMA STRIKE', imageSrc: 'https://i.ibb.co/SXC6TcSb/t14.jpg', description: "Project a bolt of lightning at a foe! Requires a lot of precision, so it's hard to hit quick targets. However, it's the real deal, with thunder that can be heard for miles, a surface of the sun, and powerful blinding light! It will take a few seconds to charge another bolt.", grade: 'kaarn' },
    { id: 'thermal_weaponry', title: 'THERMAL WEAPONRY', imageSrc: 'https://i.ibb.co/8qm4WL9/t15.png', description: "{i}Requires {y}Thermosword.{/y}{/i} Have no fear, loyal customer! These little black rods may look useless, but they're actually channels for any thermal power you can pass through them into a weapon! Design a {w}Bladed Melee{/w} or {w}Blunt Melee{/w} for {w}30 Weapon Points{/w} on the {i}Reference Page{/i}.", requires: ['thermosword'], grade: 'lekolu' },
];
