
import type { FallenPeaceSigil, FallenPeacePower } from '../../types';

// Fallen Peace
export const FALLEN_PEACE_DATA = {
    title: "THE BLESSING OF FALLEN PEACE",
    imageSrc: "/images/9HXMmkzC-main4.png",
    description: `These mages are much maligned by some, considered cowards and cheaters... but they're respected by others, for they often solve conflicts without violence. Conquering a mage through telepathy is very different than through open combat. It quickly becomes a match-up of sheer willpower, wherein the slightest lapse in concentration, even a instant of distraction, could mean a complete mental takeover. Be wary, though; if you try to take over the mind of someone of much stronger will than yourself, they may turn the tables and fry your brain!

Another bonus of taking this blessing is that you'll know from experience just the right ways to ward off psychic assaults by other telepaths. A battle between two telepaths is truly a remarkable sight! Even if, I admit, most of it's going on inside their heads...`
};

export const FALLEN_PEACE_SIGIL_TREE_DATA: FallenPeaceSigil[] = [
    { id: 'left_brained', title: 'LEFT BRAINED', description: "I guess minds aren't so complicated after all.", imageSrc: '/images/SFbsP2R-juathas.png', prerequisites: [], type: 'Left Brained', benefits: { telepathy: 1 } },
    { id: 'parietal_lobe', title: 'PARIETAL LOBE', description: '', imageSrc: '/images/zTm8fcLb-kaarn.png', prerequisites: ['left_brained'], type: 'Lobe', benefits: { telepathy: 1 } },
    { id: 'brocas_area', title: "BROCA'S AREA", description: '', imageSrc: '/images/zTm8fcLb-kaarn.png', prerequisites: ['left_brained'], type: 'Lobe', benefits: { telepathy: 1 } },
    { id: 'frontal_lobe', title: 'FRONTAL LOBE', description: '', imageSrc: '/images/Dg6nz0R1-purth.png', prerequisites: ['parietal_lobe', 'brocas_area'], type: 'Frontal Lobe', benefits: { mentalManipulation: 2 } },
    { id: 'cerebellum', title: 'CEREBELLUM', description: '', imageSrc: '/images/Dg6nz0R1-purth.png', prerequisites: ['frontal_lobe'], type: 'Lobe', benefits: { mentalManipulation: 1 } },
    { id: 'temporal_lobe', title: 'TEMPORAL LOBE', description: '', imageSrc: '/images/Dg6nz0R1-purth.png', prerequisites: ['frontal_lobe'], type: 'Lobe', benefits: { mentalManipulation: 1 } },
    { id: 'right_brained', title: 'RIGHT BRAINED', description: 'Unlocks Breaker of Minds', imageSrc: '/images/rfs5FtF3-xuth.png', prerequisites: ['cerebellum', 'temporal_lobe'], type: 'Right Brained', benefits: { mentalManipulation: 1 }, unlocks: 'breaker_of_minds' },
];

export const TELEPATHY_DATA: FallenPeacePower[] = [
    { id: 'thoughtseer', title: 'THOUGHTSEER', imageSrc: '/images/s9dW4TRR-c1.png', description: "Just by looking at someone, you can know the general subject they're thinking about and the emotions that they're feeling. You'll become excellent at manipulating people, as you'll sense just how they'll react to everything you might say, so you'll know just how to get what you want.", grade: 'kaarn' },
    { id: 'lucid_dreamer', title: 'LUCID DREAMER', imageSrc: '/images/932qDS4b-c2.jpg', description: "You not only have full control of your own dreams, but you can invade the dreams of anybody on earth while you're both sleeping and take control of all events. Levels of vividness and detail are vastly increased. Torment foes with nightmares, or even transmit covert messages to allies across distances.", grade: 'kaarn' },
    { id: 'memory_lane', title: 'MEMORY LANE', imageSrc: '/images/4ntvw4k4-c3.jpg', description: "You can see into a person's memory by focusing on them, though the farther back the memories are, the more vague and unclear they become. Things they have to remember often are particularly clear, such as passcodes, secrets, locations of hideouts and treasures, and other things they won't share.", grade: 'kaarn' },
    { id: 'mental_block', title: 'MENTAL BLOCK', imageSrc: '/images/WvKH0sn1-c4.jpg', description: "You can perform rituals that create telepathic blocks in yourself or others. Want to make a certain memory off-limits? Prevent yourself from being made to feel a certain emotion? With only a few blocks, they're unbreakable except by a {r}Breaker of Minds{/r}, but the more blocks, the weaker each is.", grade: 'kaarn' },
];

export const MENTAL_MANIPULATION_DATA: FallenPeacePower[] = [
    { id: 'perfect_stranger', title: 'PERFECT STRANGER', imageSrc: '/images/L4NDtHn-c5.png', description: "A \"stealth\" ability. When active, anyone who sees you will soon forget you were present. The duration depends on how focused they were on you. For example, if you were in combat with them, it will take minutes for them to forget you were there; if they only glanced you pass by, it will take seconds.", grade: 'purth' },
    { id: 'masquerade', title: 'MASQUERADE', imageSrc: '/images/R4c7C2Gn-c6.jpg', description: "At will, you can emanate a field that forces all around you to see you as having the same voice and appearance of a person of your choice. They will also feel a strong compelling drive to believe you {i}are{/i} that person regardless of how improbable it is, even if you hardly know how to emulate them.", grade: 'purth' },
    { id: 'psychic_vampire', title: 'PSYCHIC VAMPIRE', imageSrc: '/images/dwCXj4tm-c7.jpg', description: "When activated, you can absorb particularly powerful emotions from the people around you like a sponge. Then, you can focus your psychic energy on a target to fill them with a payload of collected emotions. Make a foe surrender by filling them with terror, or make them relax with bliss and comfort.", grade: 'purth' },
    { id: 'breaker_of_minds', title: 'BREAKER OF MINDS', imageSrc: '/images/ymp2vB3Q-c8.jpg', description: "{i}Requires {r}Right Brained.{/r}{/i} You have considerable influence over vulnerable minds. You can easily manipulate people in conversation, causing them to believe the unbelievable or coercing them to do the unthinkable. You can focus psychic energy on enemies to make them miss shots, whiff spells or be overcome with emotion. With certain lengthy rituals, you can turn 10 defeated foes into \"agents\". \n - {w}Sleeper Agent{/w}: They will forget all about their meeting with you and go about their lives none the wiser. Upon hearing a certain code phrase, they will be reduced to a mindless drone equivalent to {g}Hypnotist{/g}, but without a time limit. Once released again, they will forget all about it. Be warned it will be extremely obvious they're hypnotized, and their allies may try to free them. \n - {w}Active Agent{/w}: They will retain much of their agency and personality, but will abandon their loyalties and become subservient to you. They will march in line with your whims, but a dim part of their old self will still exist within them, causing them to (rarely) resist certain demands their old self would've considered particularly unconscionable. Agents can be freed by rituals and telepaths.", requires: ['right_brained'], grade: 'xuth' },
    { id: 'master_telepath', title: 'MASTER TELEPATH', imageSrc: '/images/nH94QpV-c9.jpg', description: "If you can control someone's perception, you can control their entire reality. At will, you will be able to induce vivid hallucinations of your choice in those around you, though you can't change how they see you. Those who see it coming and have high willpower might not fall for them, however.", grade: 'purth' },
    { id: 'crowd_control', title: 'CROWD CONTROL', imageSrc: '/images/dwKf4zGK-c10.png', description: "Mages often can defend themselves from psychic intrusion, but mundanes are usually completely vulnerable. When active, you can take complete psychic control over entire crowds of regular civilians with no time limit. Incredibly fragile, but good against mages who avoid civilian casualties.", grade: 'purth' },
    { id: 'hypnotist', title: 'HYPNOTIST', imageSrc: '/images/ymynB07C-c11.png', description: "You are adept at hypnotizing targets using regular means if they are either tricked or subdued. Victims become mindless drones that can be piloted like an extension of yourself for a few hours, though they'll still resist self harm. You will struggle making them use any spells which you do not share.", grade: 'purth' },
];
