
import type { GoodTidingsSigilTier, ChoiceItem } from '../../types';

export const GOOD_TIDINGS_DATA = {
    title: "THE BLESSING OF GOOD TIDINGS",
    imageSrc: "/images/4ZTSFgvF-main4.jpg",
    description: `This Blessing is pretty much used by every mage who's ever lived — I genuinely can't think of a single one who hadn't taken it, or at least, not one who survived long enough to be remembered. There was a time, during the war, that the Mother considered making this the only Blessing people were allowed access to, but the arrival of the Allmillor put the kibosh on that. Perhaps most important is the included durability. Battles between mages can go on for hours, and even when at the point they'd normally die, they instead fall unconscious. Killing a mage would essentially require you to {i}coup de grâce{/i} them while they're knocked out, which is still surprisingly difficult. This blessing cannot be applied to weapons.`
};

export const GOOD_TIDINGS_SIGIL_TREE_DATA: GoodTidingsSigilTier[] = [
    { id: 'standard', title: 'STANDARD', description: 'The regular kit expected of every mage.', benefits: '+3 Essential Boons', cost: 'Costs 0 BP', imageSrc: '/images/zTm8fcLb-kaarn.png' },
    { id: 'journeyman', title: 'JOURNEYMAN', description: 'You far exceed the human limits in a few extra ways.', benefits: '+4 Minor Boons', cost: 'Costs 5 BP', imageSrc: '/images/Dg6nz0R1-purth.png' },
    { id: 'master', title: 'MASTER', description: 'You are far beyond a normal human, to you, they are ants.', benefits: '+1 Major Boon', cost: 'Costs 10 BP', imageSrc: '/images/rfs5FtF3-xuth.png' }
];

export const ESSENTIAL_BOONS_DATA: ChoiceItem[] = [
    { id: 'flight', title: 'FLIGHT', cost: '', description: "With enough practice, you'll be able to fly agilely through the air with absolute ease! A pair of wings or a flying broomstick is stylish but optional. When soaring in one direction for long enough, you can reach upwards of 200 MPH, although changing direction is much slower the faster you're going.", imageSrc: '/images/RdkTwdp-b1.jpg', grade: 'kaarn' },
    { id: 'extreme_durability', title: 'EXTREME DURABILITY', cost: '', description: "Your will to survive strengthens your body in dangerous situations. Regular bullets will bounce off you, and falling from a mile's height will only bruise you; only magic has any chance of harming you. Even if you do take extreme damage, you'll likely just pass out rather than outright die.", imageSrc: '/images/1tj5QfXk-b2.jpg', grade: 'kaarn' },
    { id: 'superhuman_physicality', title: 'SUPERHUMAN PHYSICALITY', cost: '', description: "Toss a five ton truck at your enemies, outrun a speeding race car, resist any mundane poison or disease, leap and flip like an olympic acrobat, hold your breath indefinitely... mages may not always look tough, but even the weakest among them is terrifying compared to a regular human!", imageSrc: '/images/yB6KzqbQ-b3.jpg', grade: 'kaarn' },
];

export const MINOR_BOONS_DATA: ChoiceItem[] = [
    { id: 'quick_twitch', title: 'QUICK TWITCH', cost: '', description: "Your hand-eye coordination and ability to process stimuli is perfected, making you more perceptive and observant, and allowing you to react to things nearly instantly. This will allow you to, say, rapidly pull out your gun and hit a precise shot, or activate a force field milliseconds before a surprise attack.", imageSrc: '/images/qL5XGGmP-b4.jpg', grade: 'kaarn' },
    { id: 'incredible_will', title: 'INCREDIBLE WILL', cost: '', description: "You have such incredible willpower that it's almost scary! Your pain tolerance is elevated tenfold to the point that injuries barely slow you down, and it's harder for you to lose your nerve or concentration. You are also massively strengthened against, but not {i}immune{/i} to, psychic mental manipulation.", imageSrc: '/images/JFtxwBCG-b5.jpg', grade: 'kaarn' },
    { id: 'sensory_master', title: 'SENSORY MASTER', cost: '', description: "All of your senses are fine-tuned, able to pick up the tiniest sounds and smells, but you're at no risk of being overwhelmed by, say, loud noises. You can also pick out individual noises, like a conversation, even in a cacophony of a thousand sounds, and your eyesight is great even in pitch darkness.", imageSrc: '/images/mCvPByWZ-b6.png', grade: 'kaarn' },
    { id: 'cowards_boon', title: "COWARD'S BOON", cost: '', description: "Specifically when you are being chased by a foe, your maximum flying speed is boosted to 150%. This is good for 'tactical' retreats, racing, and for keeping a melee fighter from closing the distance. Your acceleration isn't boosted much, though, so don't expect to be able to get away on a dime.", imageSrc: '/images/ZRKCYFSH-b7.jpg', grade: 'kaarn' },
    { id: 'charisma_plus', title: 'CHARISMA +', cost: '', description: "You're far more charismatic than all but the suavest mundanes have any hope of being. Your persuasive ability is massively amplified, enough to get people to completely change their worldviews if you can get them to hear you out enough. You always know just what to say to get what you want.", imageSrc: '/images/8LL05BdP-b8.jpg', grade: 'kaarn' },
    { id: 'strength_plus', title: 'STRENGTH +', cost: '', description: "Exactly what it says on the tin. Now, you won't even strain to lift something until it reaches well into a hundred tons of weight, and your punches will shatter titanium hulls and can knock the wind out of even the toughest mages. And no, don't worry, you don't have to get buff for this.", imageSrc: '/images/JFpR5vnv-b9.png', grade: 'kaarn' },
    { id: 'speed_plus', title: 'SPEED +', cost: '', description: "Not only are you more swift and agile in all situations, but your speed and grace while flying is massively increased! Your maximum speed is boosted to 300 MPH, but that's not its true hard cap: from there, you can very slowly accelerate up to 400 MPH. Good luck turning, however.", imageSrc: '/images/c95thD3-b10.jpg', grade: 'kaarn' },
    { id: 'smarts_plus', title: 'SMARTS +', cost: '', description: "You've got an intellect that would be impressive even at a Mensa meeting, and a knack for thinking quickly and coming up with viable strategies while in the heat of battle. Your ability to calculate and remember is boosted greatly. You can also tell when someone is trying to psychically manipulate you.", imageSrc: '/images/1GK3Lcyp-b11.jpg', grade: 'kaarn' },
];

export const MAJOR_BOONS_DATA: ChoiceItem[] = [
    { id: 'hokuto_senjukai_ken', title: 'HOKUTO SENJUKAI KEN', cost: '', description: "{i}Requires {w}Strength +.{/w}{/i} Your strength is so incredible, you can now hold up an 18-wheeler with a pinky finger. A single punch can crack a 25,000-ton boulder into two halves and send other mages flying practically into the stratosphere, and pins are nearly inescapable. In fact, punching the air can create a blast of concussive force that will shatter all windows for a mile and deflect even magical attacks. This, combined with your vast knowledge of martial arts, will allow you to make quick work of even the toughest foes if you close the distance.", imageSrc: '/images/XkK62Tfs-b12.jpg', requires: 'strength_plus', grade: 'xuth' },
    { id: 'dont_blink', title: "DON'T BLINK", cost: '', description: "{i}Requires {w}Speed +.{/w}{/i} In bursts, you can now move fast enough that time moves so down, to the point that it's considered teleporting. This is absolutely exhausting, though, so don't overuse it or you'll crash and nap for a week. Plus, the rate at which you charge and use spells isn't sped up, and you need to be gentle when interacting with things, because Newton's third law still applies. So, if you punch someone while moving at super speed, they'll get messed up, but you'll get equally messed up. It's usually better to temporarily leave the super speed state before attacking.", imageSrc: '/images/yJ7j4kY-b13.jpg', requires: 'speed_plus', grade: 'xuth' },
    { id: 'superpowered_mind', title: 'SUPERPOWERED MIND', cost: '', description: "{i}Requires {w}Smarts +.{/w}{/i} Your brain operates like a supercomputer, and is capable of solving complex problems and equations in a matter of milliseconds, and has a eidetic memory that can hold limitless information indefinitely. Such is its might that you are totally immune to psychic interference by anybody but those rare few who rival you in intellect. Your calculation ability allows you to form predictive models of the near future with high levels of certainty, though gaps in your knowledge can affect these models' accuracies significantly.", imageSrc: '/images/3YFc3yqh-b14.jpg', requires: 'smarts_plus', grade: 'xuth' },
];
