
import type { GraciousDefeatSigil, GraciousDefeatPower } from '../../types';

export const GRACIOUS_DEFEAT_DATA = {
    title: "THE BLESSING OF GRACIOUS DEFEAT",
    imageSrc: "/images/N6q8pdqh-main5.jpg",
    description: `What a shame. Such a beautiful and fascinating blessing... marred by such a terrible history. The Sinthrus used it once to inflict the most horrid torments upon their enemies, nominally to make them endure the same torture they put the Child of God through. It is said that the {t}Broken Daughter{/t} was created this way — not that I should speak of such things...

Where some see tragedy, others see only opportunity. You see, verses are essentially tiny simulated universes existing in a sort of metaphysical 'orbit' around our own... and in the wake of the aforementioned nastiness, nobody wanted to touch them, so Nero Inc seized the opportunity to buy up all the real estate! Our reality only has so much processing power with which to handle all these verses, after all. But yeah, at the start, your verse is just going to be a simple, plain, flat black void. If you really want to spruce up the place, you're gonna have to cough up some dough...`
};

export const GRACIOUS_DEFEAT_SIGIL_TREE_DATA: GraciousDefeatSigil[] = [
    { id: 'gd_fireborn', title: 'FIREBORN', description: 'Your education into fire has begun.', imageSrc: '/images/SFbsP2R-juathas.png', prerequisites: [], type: 'Fireborn', benefits: { entrance: 1, features: 2 } },
    { id: 'cultivate_i', title: 'CULTIVATE I', description: '', imageSrc: '/images/zTm8fcLb-kaarn.png', prerequisites: ['gd_fireborn'], type: 'Cultivate', benefits: { features: 1 } },
    { id: 'realmkeeper', title: 'REALMKEEPER™', description: 'Join hundreds of happy customers!', imageSrc: '/images/DD9xYmP9-lekolu.png', prerequisites: ['gd_fireborn'], type: 'Realmkeeper', benefits: { influence: 1, features: 2 } },
    { id: 'cultivate_ii', title: 'CULTIVATE II', description: '', imageSrc: '/images/zTm8fcLb-kaarn.png', prerequisites: ['cultivate_i'], type: 'Cultivate', benefits: { features: 1 } },
    { id: 'strengthen_i', title: 'STRENGTHEN I', description: '', imageSrc: '/images/Dg6nz0R1-purth.png', prerequisites: ['realmkeeper'], type: 'Strengthen', benefits: { influence: 1 } },
    { id: 'sweet_suffering', title: 'SWEET SUFFERING', description: 'Unlocks Gathoth Puzzle', imageSrc: '/images/nq80Y3pk-sinthru.png', prerequisites: ['strengthen_i'], type: 'Sweet Suffering', benefits: { influence: 1 }, unlocks: 'gathoth_puzzle' },
    { id: 'realmmaster', title: 'REALMMASTER™', description: 'Unlocks Advanced Verse Package', imageSrc: '/images/DD9xYmP9-lekolu.png', prerequisites: ['strengthen_i'], type: 'Realmmaster', benefits: { influence: 1, features: 2 }, unlocks: 'advanced_verse_package' },
    { id: 'pocket_god', title: 'POCKET GOD', description: 'Unlocks Reality Invasion', imageSrc: '/images/rfs5FtF3-xuth.png', prerequisites: ['realmmaster'], type: 'Pocket God', benefits: { influence: 1 }, unlocks: 'reality_invasion' },
    { id: 'strengthen_ii', title: 'STRENGTHEN II', description: '', imageSrc: '/images/Dg6nz0R1-purth.png', prerequisites: ['realmmaster'], type: 'Strengthen', benefits: { influence: 1 } },
];

export const ENTRANCE_DATA: GraciousDefeatPower[] = [
    { id: 'painted', title: 'PAINTED', imageSrc: '/images/hxwxmbjT-d1.png', description: "You painted your verse into existence. Quite an awe-inspiring work, too; even not knowing its true nature, people find themselves drawn to its mesmerizing aura. Getting to your verse is as easy as jumping headlong into your painting. Just be careful not to let it get lost or burn up!", grade: 'kaarn' },
    { id: 'momento', title: 'MOMENTO', imageSrc: '/images/v64y1fmx-d2.png', description: "You verse is based upon a treasured memory. Thus, a momento can be used to temporarily open a portal that anybody can exit and enter through. This requires a ritual that takes much less time than {i}Within{/i}, but much more than {i}Painted{/i}. At least the momento can be a lot more durable and hideable.", grade: 'kaarn' },
    { id: 'within', title: 'WITHIN', imageSrc: '/images/GvLyQ4Bq-d3.jpg', description: "Your verse exists within yourself; therefore, there's no chance of it getting lost or destroyed, unless you forget about it. However, it will require hours of deep, serious meditation and introspection to enter. To visit, others will have to do the same while making physical contact with you.", grade: 'kaarn' },
    { id: 'gathoth_puzzle', title: 'GATHOTH PUZZLE', imageSrc: '/images/GLJBWxz-d4.jpg', description: "{i}Requires {bp}Sweet Suffering.{/bp}{/i} During the Sinthru Doctrine, this was the only way to enter verses. To enter your verse, a puzzle box must be solved; if you can fool or force someone into solving the puzzle, it will be extremely difficult for them to escape from your verse unless you let them out.", requires: ['sweet_suffering'], grade: 'sinthru' },
];

export const FEATURES_DATA: GraciousDefeatPower[] = [
    { id: 'natural_environment', title: 'NATURAL ENVIRONMENT', imageSrc: '/images/b8HvHJr-d5.jpg', description: "Adds 30 acres of any sort of wilderness you want to your verse. Doesn't even have to make geological sense, really. Just go nuts! You won't have to deal with any of the downsides to environments you pick, either. Not very big, but can be taken multiple times; each time, it doubles the acreage.", grade: 'kaarn' },
    { id: 'artificial_environment', title: 'ARTIFICIAL ENVIRONMENT', imageSrc: '/images/PzZBpstp-d6.jpg', description: "Adds 30 acres of any sort of civilized area you want to your verse. From cities, to towns, to scattered buildings, all fitting in with the environment. If you have no real inhabitants, though, it will all be abandoned. Not very big, but can be taken multiple times; each time, it doubles the acreage.", grade: 'kaarn' },
    { id: 'shifting_weather', title: 'SHIFTING WEATHER', imageSrc: '/images/C5qzYThh-d7.jpg', description: "By default, your verse will be one of endless night on a cloudless day with a mild temperature. With this, you can shake things up a bit. You can stick to realistic weather events, or go crazy with it. Want to watch a supernova in the sky every night? A volcano that erupts lightning instead of lava?", grade: 'kaarn' },
    { id: 'living_inhabitants', title: 'LIVING INHABITANTS', imageSrc: '/images/pvGVPyr8-d8.jpg', description: "Adds a new species of native life to your verse. Can choose between two species types: very highly populated ones, who you can design with {w}40 Beast Points{/w}, or rarer ones with fewer individuals, which you can design with {w}70 Beast Points{/w} on the {i}Reference Page{/i}. Can be taken multiple times.", grade: 'kaarn' },
    { id: 'broken_space', title: 'BROKEN SPACE', imageSrc: '/images/1hXCpyN-d9.jpg', description: "The environments you create within your verse are unbound by laws of physics and reason. Create a place that folds in on itself, twisting upside down in places and sideways in others, or etc. Note that it affects where you're immediately standing, so you cannot make it impossible to survive or navigate.", grade: 'kaarn' },
    { id: 'broken_time', title: 'BROKEN TIME', imageSrc: '/images/TMd0WRBT-d10.jpg', description: "Time is all subjective, you know. This feature lets you choose how time moves differently from the 'real' world. This can range from a day in the verse being a week in real time, or vice versa. You can also set it to vary depending on one's location within the verse, or even from person to person.", grade: 'kaarn' },
    { id: 'promised_land', title: 'PROMISED LAND', imageSrc: '/images/Sj84yc9-d11.png', description: "Verses are resource intensive things, and there's only so much processing power to go around. By default, only around 15 other people can visit your verse at the same time before serious errors will occur. This option can be taken multiple times; each time, it doubles the population limit of your verse.", grade: 'kaarn' },
    { id: 'verse_attendant', title: 'VERSE ATTENDANT', imageSrc: '/images/G3PrvJXy-d12.jpg', description: "Adds a human caretaker to your verse, charged with keeping things tidy in your stead while you are away. You can design them with {w}50 Companion Points{/w} on the {i}Reference Page{/i}. Not too practical, but it will be nice to see a friendly face every time you visit. Can be taken multiple times.", grade: 'kaarn' },
];

export const INFLUENCE_DATA: GraciousDefeatPower[] = [
    { id: 'advanced_verse_package', title: 'ADVANCED VERSE PACKAGE', imageSrc: '/images/BKqYq4hV-d13.jpg', description: "{i}Requires {y}Realmmaster™.{/y}{/i} We here at Nero Inc want you to feel the power of a God at your fingertips! With this package, your verse will no longer be static; you'll be able to change the landscape, weather, and everything else with your thoughts alone! You will truly be its undisputed master!", requires: ['realmmaster'], grade: 'lekolu' },
    { id: 'summon_creature', title: 'SUMMON CREATURE', imageSrc: '/images/cKMXwGFS-d14.jpg', description: "{i}Requires {w}Living Inhabitants.{/w}{/i} Open portals just long enough to summon a few monsters native to your verse into the 'real' world! Unlike your familiar, you will be able to summon multiple before they'll be forced to return to their realm.", requires: ['living_inhabitants'], grade: 'kaarn' },
    { id: 'summon_attendant', title: 'SUMMON ATTENDANT', imageSrc: '/images/cSZKpWTK-d15.png', description: "{i}Requires {w}Verse Attendant.{/w}{/i} Open portals to allow your attendant to move between your verse and the real world. She will be obligated to act according to your whims, and will be invested in protecting you and the verse. Similarly to creatures, she can only stick in the 'real' world for a few hours.", requires: ['verse_attendant'], grade: 'kaarn' },
    { id: 'reality_invasion', title: 'REALITY INVASION', imageSrc: '/images/23CzLcNp-d16.jpg', description: "{i}Requires {r}Pocket God.{/r}{/i} Everywhere you go, nearby environmental conditions change to reflect those in your verse; for example, if your verse is a desert, things become warmer and arid. Stay in a place for long enough, and you can create Versestones to open tears in reality through which your verse will begin to leak. They always have to be visible and out in the open. Your verse's landscape will appear in reality in slowly growing spheres around each tear; these spheres will be considered part of your verse, and thus, your creatures and attendant can roam freely there, and your godlike powers have full sway. These spheres of influence can be destroyed by destroying the Versestones in their centers, which can be done using long-ranged attacks unless the sphere has already spread massively. Thus, many mages aim to nip any tears in the bud before they get too big to destroy easily. The closer you are to tears in reality, the easier it is to open portals to your verse, allowing spells like {w}Summon Creature{/w} to be done faster and in greater numbers. Tears in reality also act as portals, making it much easier to enter and exit your verse. The more your influence spreads in reality, the bigger and more powerful your verse itself will become.", requires: ['pocket_god'], grade: 'xuth' },
    { id: 'summon_weather', title: 'SUMMON WEATHER', imageSrc: '/images/4RmNGH7s-d17.jpg', description: "{i}Requires {w}Shifting Weather.{/w}{/i} Create chaos by opening dozens of tiny portals to flood the battlefield with a weather event from your verse! Bursts of lightning from a megastorm? Flows of lava from a volcano? Sky's the limit. Not targeted, so better for area control than direct combat.", requires: ['shifting_weather'], grade: 'kaarn' },
    { id: 'overlord', title: 'OVERLORD', imageSrc: '/images/b5NzzRdS-d18.jpg', description: "While within the boundaries of your Verse, you not only have control of the world around you, but your own form. You assume a godlike shape while within your verse, which you can design with {w}Infinite Beast Points{/w} on the {i}Reference Page{/i}, excluding any options marked with a *.", grade: 'kaarn' },
    { id: 'soul_harvest', title: 'SOUL HARVEST', imageSrc: '/images/5hcgQpXy-d19.jpg', description: "{i}Requires {bp}Gathoth Puzzle.{/bp}{/i} Ordinarily, no visitors can die in your verse; they will merely respawn. With this, death for them is permanent, though it is for you, too, if they fight back. Killing mages in particular in your realm will cause it to grow in size and boost the strength of your influences.", requires: ['gathoth_puzzle'], grade: 'sinthru' },
];
