
import type { LostHopeSigil, LostHopePower } from '../../types';

export const FIDELIA_DATA = {
    title: "FIDELIA, DAUGHTER OF UNDERSTANDING",
    imageSrc: "/images/ZR57tp80-main2.jpg",
    description: `The middle child among the Daughters, and by far the most mysterious and mired in rumors. Even I only rarely see her emerge from the Twilight Palace up in the Garden. Yet, at the same time, she is also the most likely to personally connect with her followers, with many reporting her appearing to them in times of great need or visiting them in their dreams. This personableness has led her to fame... and scandals. As the Sinthru covens ravaged the land, outrage spread over revelations that she'd been seen consorted with high-ranking coven members before the revolt, to the point of being Elvira's lover. And she was always the Daughter who felt the most sympathy for the Child of God...
    
Of course, the official position is that she was never involved with the Sinthru covens, and is actually just misunderstood — she is, after all, something of a patron saint for misunderstood mages. She oversees all the magic with dreadful and dark reputations — such as necromancy — but which actually hold great beauty and utility, and she supports all those who are maligned or mistreated for failing to conform to society's standards. Her campaigns have been very successful over the millenia, and now, people tend to be very accepting of even the most extreme of differences. So really, there's no need to believe those silly rumors! She's such a kind girl, it kills me to see her plagued by all these silly conspiracy theories. Especially {i}all of{/i} those absurd ones about her sealing away an entire Blessincxvqmeuywitpdrrinbojkgt.`
};

export const LOST_HOPE_DATA = {
    title: "THE BLESSING OF LOST HOPE",
    imageSrc: "/images/607svvK8-main3.jpg",
    description: `Death is basically hardcoded into our reality; once the data that once composed a person's psyche is overwritten (which only takes a matter of hours) it cannot be regained. However, certain strange phenomena blur the lines between life and death, the most famous of which being spirits. These spirits aren't the full-fledged person, but a sort of psychic echo, like the residue of all their emotions and experiences left in the halls of time, with an origin akin to Distortions. As our reality destabilizes, these spirits become more prominent, and those who control them more powerful.
    
Further research into this discipline has yielded means of imbuing those spirits into corpses in order to create creatures somewhere in between the boundaries of life and death. Even the most advanced of these grotesque creatures cannot be exactly the same person they used to be, and their new personalities trend towards being more... macabre.`
};

export const LOST_HOPE_SIGIL_TREE_DATA: LostHopeSigil[] = [
    { id: 'young_witch', title: 'YOUNG WITCH', description: '', imageSrc: '/images/SFbsP2R-juathas.png', prerequisites: [], type: 'Young Witch', benefits: { channeling: 2 } },
    { id: 'spirit_channel', title: 'SPIRIT CHANNEL', description: '', imageSrc: '/images/zTm8fcLb-kaarn.png', prerequisites: ['young_witch'], type: 'Spirit Channel', benefits: { channeling: 1 } },
    { id: 'deadseer', title: 'DEADSEER', description: 'Unlocks Life Drain', imageSrc: '/images/Dg6nz0R1-purth.png', prerequisites: ['young_witch'], type: 'Deadseer', benefits: { channeling: 1 }, unlocks: 'life_drain' },
    { id: 'necromancer', title: 'NECROMANCER', description: '', imageSrc: '/images/Dg6nz0R1-purth.png', prerequisites: ['spirit_channel'], type: 'Necromancer', benefits: { necromancy: 1 } },
    { id: 'forbidden_arts_i', title: 'FORBIDDEN ARTS I', description: '', imageSrc: '/images/nq80Y3pk-sinthru.png', prerequisites: ['deadseer'], type: 'Forbidden Arts', benefits: { blackMagic: 1 } },
    { id: 'lazarus', title: 'LAZARUS', description: 'Unlocks The Moon Samurai', imageSrc: '/images/Dg6nz0R1-purth.png', prerequisites: ['necromancer'], type: 'Lazarus', benefits: { necromancy: 2 }, unlocks: 'the_moon_samurai' },
    { id: 'forbidden_arts_ii', title: 'FORBIDDEN ARTS II', description: '', imageSrc: '/images/nq80Y3pk-sinthru.png', prerequisites: ['necromancer'], type: 'Forbidden Arts', benefits: { blackMagic: 1 } },
    { id: 'forbidden_arts_iii', title: 'FORBIDDEN ARTS III', description: '', imageSrc: '/images/nq80Y3pk-sinthru.png', prerequisites: ['lazarus'], type: 'Forbidden Arts', benefits: { blackMagic: 1 } },
    { id: 'lich_queen', title: 'LICH QUEEN', description: 'Unlocks Flowers of Blood', imageSrc: '/images/rfs5FtF3-xuth.png', prerequisites: ['lazarus'], type: 'Lich Queen', benefits: { blackMagic: 1 }, unlocks: 'flowers_of_blood' },
];

export const CHANNELLING_DATA: LostHopePower[] = [
    { id: 'spirit_medium', title: 'SPIRIT MEDIUM', imageSrc: '/images/qYcLvjjC-b1.jpg', description: "Through all sorts of various means, you can ask questions of the remnants of any dead person's soul. They couldn't lie to you if you wanted to, so you can obtain {i}all{/i} of their knowledge. Just be careful. Dead men {i}do{/i} tell tales — but sometimes it's better if those tales had died with them.", grade: 'kaarn' },
    { id: 'fata_morgana_curse', title: 'FATA MORGANA CURSE', imageSrc: '/images/MxhYZ0vz-b2.jpg', description: "All it requires is a ritual and a strand of a victim's hair. Poltergeists will sabotage their lives, whisper in the ears of their friends and drive them away, and cause them to whiff spells at vital moments. Can be subtle to be nearly undetectable as a curse, or can be elevated into a full-blown haunting.", grade: 'kaarn' },
    { id: 'spectral_form', title: 'SPECTRAL FORM', imageSrc: '/images/HTWWzLNL-b3.jpg', description: "You can shift yourself into a spectral form for an hour or two through a minutes-long ritual. You will be incorporeal and impossible for a non-necromancer to damage, but you can't use your powers. You can be invisible to most mages and all mundanes, and can move and manipulate objects like a poltergeist.", grade: 'kaarn' },
    { id: 'life_drain', title: 'LIFE DRAIN', imageSrc: '/images/WNxV5jRM-b4.jpg', description: "{i}Requires {g}Deadseer.{/g}{/i} Every few seconds you can fire a projectile that latches a small spirit leech to a foe. These can be removed, but are hard to find on the body as they are small and near-invisible. Each very slowly sucks life energy from your foe and sends it to you, gradually rejuvenating and healing you.", requires: ['deadseer'], grade: 'purth' },
];

export const NECROMANCY_DATA: LostHopePower[] = [
    { id: 'undead_beast', title: 'UNDEAD BEAST', imageSrc: '/images/WZxGTKd-b5.jpg', description: "You will be able to revive the body of a great and mythological creature, and bind it to your soul so that it may always serve you. If your guardian creature is ever killed or injured, it can simply stitch itself back together, piece by piece. Design it with {w}60 Beast Points{/w} on the {i}Reference Page{/i}.", grade: 'kaarn' },
    { id: 'rise_from_your_graves', title: 'RISE FROM YOUR GRAVES', imageSrc: '/images/KpqpjH4D-b6.jpg', description: "A quick ritual that reforms everybody who has ever perished in an area, usually bringing back a couple dozen zombies. They have supernatural strength and speed, though they're relatively fragile and can't fly. They also infect every mundane human they bite, so, uh, try not to start a major outbreak.", grade: 'kaarn' },
    { id: 'grasping_dead', title: 'GRASPING DEAD', imageSrc: '/images/yFqw8Lqy-b7.jpg', description: "Can form a {i}massive{/i} ball of decaying, powerful limbs and half-assembled bodies, before projecting it at a target with incredible force. If it collides, not only will it do significant damage, but the victim will become stuck in a tangled ball of tightly grasping, strong limbs, leaving them open to further attacks.", grade: 'kaarn' },
    { id: 'the_moon_samurai', title: 'THE MOON SAMURAI', imageSrc: '/images/3mNP4Mth-b8.jpg', description: "{i}Requires {g}Lazarus.{/g}{/i} Jipangu was {i}de facto{/i} ruled over by its samurai warriors until the Empress reclaimed power and cursed her foes to never find peace. Now, many small armies of unkillable, powerful ghost warriors work as mercenaries in exchange for souls. The more souls, the longer they serve you.", requires: ['lazarus'], grade: 'purth' },
];

export const BLACK_MAGIC_DATA: LostHopePower[] = [
    { id: 'undead_thrall', title: 'UNDEAD THRALL', imageSrc: '/images/M0cSVF7-b9.png', description: "To revive a mundane is, for a necromancer, trivial and can be done en masse. But to revive a mage defies the will of the Mother, and is an altogether risker art. You can now revive your fallen foes into zombielike, mindless versions of their past selves, though they'll lack large portions of their old power and intelligence. Mages are horrified by the threat of being turned into one of these flesh puppets. You're also good enough to create one true Thrall, a rare and powerful undead with some soul still intact, designed with {w}50 Companion Points{/w}.", grade: 'sinthru' },
    { id: 'vampirism', title: 'VAMPIRISM', imageSrc: '/images/Txyw78RQ-b10.jpg', description: "Involves technically giving up your life only to immediately revive yourself as an undead creature. Vampires are known for their supernatural beauty and charisma, but blood withdrawal can turn them into gaunt, weak things. Sunlight burns with gradually increasing intensity upon their skin. However, drinking blood boosts their strength, speed and durability; those who've consumed, say, a hundred barrels reach twice the aptitude of an average mage. Draining a mage to death allows you to steal one non-{r}Xuth{/r}-tier power for months.", grade: 'sinthru' },
    { id: 'cursemakers_cookbook', title: "CURSEMAKER'S COOKBOOK", imageSrc: '/images/bRPQXz5x-b11.png', description: "With a DNA sample like a strand of a victim's hair, you can subject them to a curse based on one of your other powers. For example, with {w}Pyromancer{/w}, they may feel a constant burning pain; with {w}Rise from your Graves{/w}, all nearby dead may rise and attack them; and etc. Click the book icon to view the Curse Encyclopedia. Additionally, once a century under the rare Witching Moon, you can curse a person and everyone who shares their blood, and it can only be removed if you die or remove it yourself.", grade: 'sinthru' },
    { id: 'flowers_of_blood', title: 'FLOWERS OF BLOOD', imageSrc: '/images/vvjRnPmd-b12.jpg', description: "{i}Requires {r}Lich Queen.{/r}{/i} The feared archlich Elvira, head of the first Sinthru coven before she was captured, was known for watering an enchanted garden with the blood of her foes. While your garden remains undestroyed and watered with a human's worth of blood on a weekly basis, you are unkillable. You are essentially an invincible skeleton piloting a comfortable meat suit; even if everything else is burned away, your skeleton will remain and still be animate (albeit significantly weakened), unable to be destroyed even by the core of the sun.", requires: ['lich_queen'], grade: 'xuth' }
];
