
import type { RighteousCreationSigil, SpecialtyChoice, RighteousCreationPower } from '../../types';

// Righteous Creation
export const RIGHTEOUS_CREATION_DATA = { 
    title: "THE BLESSING OF RIGHTEOUS CREATION", 
    imageSrc: "https://i.ibb.co/Fb149kMB/main3.jpg", 
    description: "The Blessing most enjoyed by the more innovative and entrepreneurial of mages, and the one responsible for nearly all of the amazing inventions that characterize modern life. Metamagic was its earliest form, back in the very primal eras; shortly {i}after{/i} {i}Theosis{/i}, almost everyone on Earth enjoyed some level of magical ability, and they experimented with ways to push these powers to the limits. As society grew more complex, we even learned how to harness arcane matter. Once upon a time, the mere presence of a mage would incur surges, saps and dips in all nearby electrical circuits, but nowadays, most electronics have been thoroughly “magic-proofed” (although powerful spells or big battles have still been known to cause blackouts). This has brought on a new era of magitech, which has birthed some incredible luxuries. The difference between them all, can, perhaps, be most easily explained by the continuum between tech and magic. Magitech is heavy on the tech side of things, and metamagic on the magic side, while arcane constructs are half-and-half." 
};
export const RIGHTEOUS_CREATION_SIGIL_TREE_DATA: RighteousCreationSigil[] = [
    { id: 'rookie_engineer', title: 'ROOKIE ENGINEER', description: '', imageSrc: 'https://i.ibb.co/SFbsP2R/juathas.png', prerequisites: [], benefits: { specialty: 1 } },
    { id: 'polymat', title: 'POLYMATH™', description: 'Take the Vex Co. training regimen for instant results!', imageSrc: 'https://i.ibb.co/DD9xYmP9/lekolu.png', prerequisites: ['rookie_engineer'], benefits: { specialty: 1 } },
    { id: 'technician', title: 'TECHNICIAN', description: '', imageSrc: 'https://i.ibb.co/zTm8fcLb/kaarn.png', prerequisites: ['rookie_engineer'], benefits: { magitech: 1, arcaneConstructs: 1 } },
    { id: 'magician', title: 'MAGICIAN', description: '', imageSrc: 'https://i.ibb.co/zTm8fcLb/kaarn.png', prerequisites: ['rookie_engineer'], benefits: { metamagic: 1 } },
    { id: 'magitechnician', title: 'MAGITECHNICIAN', description: 'Unlocks Master Mechanic I', imageSrc: 'https://i.ibb.co/Dg6nz0R1/purth.png', prerequisites: ['technician'], unlocks: ['master_mechanic_i'], benefits: { magitech: 2 } },
    { id: 'arcane_wizard', title: 'ARCANE WIZARD', description: 'Unlocks Roboticist II', imageSrc: 'https://i.ibb.co/Dg6nz0R1/purth.png', prerequisites: ['technician'], unlocks: ['roboticist_ii'], benefits: { arcaneConstructs: 2 } },
    { id: 'metamagician', title: 'METAMAGICIAN', description: 'Unlocks Ace in the Hole', imageSrc: 'https://i.ibb.co/Dg6nz0R1/purth.png', prerequisites: ['magician'], unlocks: ['ace_in_the_hole'], benefits: { metamagic: 2 } },
    { id: 'master_magitech', title: 'MASTER MAGITECH', description: 'Unlocks Master Mechanic II', imageSrc: 'https://i.ibb.co/rfs5FtF3/xuth.png', prerequisites: ['magitechnician'], unlocks: ['master_mechanic_ii'], benefits: { magitech: 2 } },
    { id: 'master_arcana', title: 'MASTER ARCANA', description: 'Unlocks Divine Clay', imageSrc: 'https://i.ibb.co/rfs5FtF3/xuth.png', prerequisites: ['arcane_wizard'], unlocks: ['divine_clay'], benefits: { arcaneConstructs: 2 } },
    { id: 'metamaster', title: 'METAMASTER', description: "Unlocks Maria's Gift", imageSrc: 'https://i.ibb.co/rfs5FtF3/xuth.png', prerequisites: ['metamagician'], unlocks: ["marias_gift"], benefits: { metamagic: 2 } },
];
export const RIGHTEOUS_CREATION_SPECIALTIES_DATA: SpecialtyChoice[] = [
    { id: 'magitech_specialty', title: 'MAGITECH', imageSrc: 'https://i.ibb.co/R441YsHB/b1.jpg', description: "A discipline that focuses largely on technology, with magic only used to 'grease the wheels', so to speak, and allow your machines to operate on a level beyond what a mundane engineer would be capable of. Taking this specialty is required to take {i}any{/i} powers in the {w}Magitech{/w} category.", grade: 'kaarn' },
    { id: 'arcane_constructs_specialty', title: 'ARCANE CONSTRUCTS', imageSrc: 'https://i.ibb.co/svNL1LN9/b2.jpg', description: "The art of creating things in physical reality through the use of magic. These constructs can then be blended with technology; for example, magically creating an artificial soul to place in a mechanical body. Taking this specialty is required to take {i}any{/i} powers in the {w}Arcane Constructs{/w} category.", grade: 'kaarn' },
    { id: 'metamagic_specialty', title: 'METAMAGIC', imageSrc: 'https://i.ibb.co/Z1f6CyLD/b3.jpg', description: "The study of magic itself. While it's stereotyped as highly theoretical, it has countless practical uses if pushing your powers to their absolute limits, or expanding the arsenal of yourself and others, is what you desire. Taking this specialty is required to take {i}any{/i} powers in the {w}Metamagic{/w} category.", grade: 'kaarn' },
];

export const RIGHTEOUS_CREATION_MAGITECH_DATA: RighteousCreationPower[] = [
    { id: 'kaboom', title: 'KABOOM!', imageSrc: 'https://i.ibb.co/4ZxQx8Ys/b4.jpg', description: "You are an expert at creating explosives! You can even combine them with various magical effects, like ice, fire, electricity, music, or what have you. You can create bombs with preternaturally large yields with impressively few resources, though other mages may be able to disarm them.", grade: 'kaarn' },
    { id: 'max_security', title: 'MAX SECURITY', imageSrc: 'https://i.ibb.co/1JjHpwKW/b5.jpg', description: "You can create security systems, traps, and defenses effective even against mages. Nearly impenetrable blast doors, autoturrets that fire high explosive rounds with pinpoint accuracy, traps that freeze trespassers inside a solid block of ice, and all sorts of other neat traps and alarm systems.", grade: 'kaarn' },
    { id: 'venture_capitalist', title: 'VENTURE CAPITALIST', imageSrc: 'https://i.ibb.co/0pSRK1TW/b6.jpg', description: "You are incredibly good at inventing consumer commodities which don't have a ton of practical purposes, but which are extremely fun, useful or convenient. People will trip over themselves to buy these products, so this is a good skill to hone if your main goal is to get filthy stinkin' rich.", grade: 'kaarn' },
    { id: 'tinkerer', title: 'TINKERER', imageSrc: 'https://i.ibb.co/JjZqQj86/b7.jpg', description: "You can create advanced mundane technology out of the most absurdly useless parts, and at stunning speeds. In a few minutes, make a sci-fi weapon, suit of armor, computer, or etc out of a few boxes of scrap and tidbits. You can also repair and modify existing mundane technology nearly instantly.", grade: 'kaarn' },
    { id: 'weaponsmith', title: 'WEAPONSMITH', imageSrc: 'https://i.ibb.co/Kzpm0BNT/b8.jpg', description: "You are an expert at doling out death with maximum efficiency, and can forge entire arsenals. Create your masterpiece using {w}40 Weapon Points{/w} on the {i}Reference Page{/i}. You can also upgrade the weapons of others, granting them {w}10{/w} extra {w}Weapon Points{/w} to work with. Doesn't stack.", grade: 'kaarn' },
    { id: 'rocket_propulsion', title: 'ROCKET PROPULSION', imageSrc: 'https://i.ibb.co/G3HT97WL/b9.png', description: "Regular humans would not doubt go flying into a wall instantly using this, but with your power of flight, you're much better at steering yourself. These customized systems allow you to increase your maximum flying speed by an extra 100 MPH, on top of massively boosting your acceleration.", grade: 'kaarn' },
    { id: 'master_mechanic_i', title: 'MASTER MECHANIC I', imageSrc: 'https://i.ibb.co/zhJDc8ZL/b10.jpg', description: "{i}Requires {g}Magitechnician.{/g}{/i} You are now capable of making your own highly advanced, magically enchanted dream ride! You will be given {w}50 Vehicle Points{/w} to work with on the {i}Reference Page{/i}. You can also upgrade others' vehicles, granting them {w}10{/w} extra {w}Vehicle Points{/w} to work with. Doesn't stack.", requires: ['magitechnician'], grade: 'purth' },
    { id: 'master_mechanic_ii', title: 'MASTER MECHANIC II', imageSrc: 'https://i.ibb.co/w3Dv8Hc/b11.jpg', description: "{i}Requires {r}Master Magitech{/r} and {g}Master Mechanic I.{/g}{/i} Nothing's cooler than fighting giant monsters in a giant robot! In this spirit, you now have {w}100 Vehicle Points{/w} with which to build your dream ride. Plus, you'll know how to continually upgrade your ride and its weapons to make it even bigger and better.", requires: ['master_magitech', 'master_mechanic_i'], grade: 'xuth' },
];

export const RIGHTEOUS_CREATION_ARCANE_CONSTRUCTS_DATA: RighteousCreationPower[] = [
    { id: 'tears_in_space', title: 'TEARS IN SPACE', imageSrc: 'https://i.ibb.co/1tBD1v9X/b12.jpg', description: "This is the spell that revolutionized travel and industry in ways too innumerable to list. With a long ritual, you can open a portal in a place, and then connect two opened portals, allowing travel instantly between them. Takes some time, though, so don't expect to make one during combat.", grade: 'kaarn' },
    { id: 'roboticist_i', title: 'ROBOTICIST I', imageSrc: 'https://i.ibb.co/Gf98rSRf/b13.jpg', description: "You will be an expert at infusing simplistic artificial souls into machinery, allowing you to create a plethora of customized robots to fulfill all sorts of minor roles and conveniences. You will also be given {w}40 Beast Points{/w} on the {i}Reference Page{/i} with which to design your 'magnum opus'.", grade: 'kaarn' },
    { id: 'roboticist_ii', title: 'ROBOTICIST II', imageSrc: 'https://i.ibb.co/SDTT4cpR/b14.png', description: "{i}Requires {w}Roboticist I{/w} and {g}Arcane Wizard.{/g}{/i} Not only can your robots be more mechanically complex, but the quality of the artificial souls you create for them is also boosted almost to the point of true sapience. Create another 'magnum opus' using {w}50 Companion Points{/w} on the {i}Reference Page{/i}.", requires: ['roboticist_i', 'arcane_wizard'], grade: 'purth' },
    { id: 'divine_clay', title: 'DIVINE CLAY', imageSrc: 'https://i.ibb.co/KpqTKjq5/b15.jpg', description: "{i}Requires {r}Master Arcana{/r} and {w}Arcane Matter.{/w}{/i} You can form and sculpt glowing arcane matter like clay with your mind alone, which will, after a few seconds, solidify into a physical material of your choice, all the way from concrete to titanium. This can be done in large enough quantities to construct a palace in a matter of minutes. Mages with this ability tend to become exorbitantly wealthy as architects, building entire cities single-handedly in weeks or months. It can also be used to build complex mechanical devices in mere seconds, although you are limited to what you already know how to make. This process is also fast enough to create weapons, walls and structures to defend yourself while mid-battle; however, arcane matter is quite fragile, so these structures will be weak for the two or three seconds before they can 'solidify'.\n\nThe Red-Jade council works to continue its policy of artificial scarcity by rendering this impossible via zoning laws. They won't mind if you make some sweet digs for you and your friends, but taking over the real estate market will {i}make{/i} very powerful {i}enemies{/i}. However, all housing options and upgrades become absolutely free for you.", requires: ['master_arcana', 'arcane_matter'], grade: 'xuth' },
    { id: 'camouflage', title: 'CAMOUFLAGE', imageSrc: 'https://i.ibb.co/TxfWgc5z/b16.png', description: "You can create a camouflage texture that bends light around objects, essentially rendering them seethrough. Use this on a cloak, and you can essentially render yourself invisible. It will never even be picked up by thermals; the only sign of its existence will be a very faint shimmer.", grade: 'kaarn' },
    { id: 'all_seeing', title: 'ALL-SEEING', imageSrc: 'https://i.ibb.co/qM82bnqX/b17.png', description: "You have the ability to create arcane satellites; \"eyes in the sky\" that you can move and control through thoughts alone, all visual input being instantly relayed to your mind. Many of these can be created, although they are each limited in the area they can cover. They are very hard to spot.", grade: 'kaarn' },
    { id: 'arcane_matter', title: 'ARCANE MATTER', imageSrc: 'https://i.ibb.co/9Pb8s7Q/b18.jpg', description: "You can slowly create small amounts of arcane matter that can be refined into duplicates of objects you've saved the \"blueprints\" for; very useful for making replacements. You can even duplicate entire buildings if you don't mind spending a few weeks weaving new matter.", grade: 'kaarn' },
];

export const RIGHTEOUS_CREATION_METAMAGIC_DATA: RighteousCreationPower[] = [
    { id: 'dehexification', title: 'DEHEXIFICATION', imageSrc: 'https://i.ibb.co/211q0DFJ/b19.jpg', description: "You've extensively studied every curse and hex out there, and the long, complex rituals required to remove them. Is it kind of a boring power? Well... yes, I suppose so. But when you've been afflicted with a Reinman's Curse miles from civilization, I assure you, you'll be very happy that you took this.", grade: 'kaarn' },
    { id: 'power_share', title: 'POWER SHARE', imageSrc: 'https://i.ibb.co/qF7ZRn0c/b20.png', description: "You can share one non-Metamagic, {w}Kaarn{/w}-tier power you have with all of your teammates (must be within 10 kmn of you, can affect up to 10 people at a time). You can, instead, allow one of your allies to {w}use{/w} {w}Power Share{/w}, with the team. if multiple teammates use Power Share, it caps at 3.", grade: 'kaarn' },
    { id: 'power_theft', title: 'POWER THEFT', imageSrc: 'https://i.ibb.co/pBXwGWdH/b21.jpg', description: "By making physical contact and reciting an incantation, you can steal one power from an enemy. It must fit the guidelines for a power usable {i}by a{/i} {w}Beast{/w}, as listed on the {i}Reference Page{/i}. They can steal their power back by simply touching you, or it will be returned automatically in a half hour.", grade: 'kaarn' },
    { id: 'marias_gift', title: "MARIA'S GIFT", imageSrc: 'https://i.ibb.co/gbFxhkSc/b22.jpg', description: "{i}Requires {r}Metamaster.{/r}{/i} Typically, granting Stolen Blessings is the sole domain of the Mother, but you have achieved such a grasp of metamagic that you can emulate this ability. Think of this power as having 100 'points' you can spend at a time. For 1 point, you can grant any mundane either five {w}Kaarn{/w}-tier powers, or two {w}Kaarn{/w}-tier powers and one {g}Purth{/g}-tier power. Alternatively, you can spend 10 points to grant another mage one {c}Ruhai{/c}-tier power, or 25 for a {b}Milgrath{/b}-tier power. These can be revoked at any time for a refund. You cannot spend more points giving one person more powers.\n\nPerhaps your greatest ability is to shed your form at will and become a floating, shining ball of pure magical energy — nicknamed the titular \"Maria's Gift\". This cancels all powers granted through above means. Instead, you may enter the body of any living entity, able to see through its eyes and communicate telepathically. Until you leave their body, they will possess all your non-Metamagic powers, alongside any of their own. You cannot have multiple Gifts in the same body, nor can you cannot chain multiple Gifts into eachother like a Matryoshka doll. Used wisely, the result is invariably one of the most powerful entities in the world.", requires: ['metamaster'], grade: 'xuth' },
    { id: 'power_sight', title: 'POWER SIGHT', imageSrc: 'https://i.ibb.co/sz81vym/b23.jpg', description: "Just by looking at a mage, you can instantly know what their powers are, except their Metamagic or Sinthru ones. You can also tell what category their weakness or requirement falls into, and when a mundane is secretly a mage. Unlike mindreading, this ability completely bypasses mental blocks.", grade: 'kaarn' },
    { id: 'broken_limiter', title: 'BROKEN LIMITER', imageSrc: 'https://i.ibb.co/Z6kmKnfX/b24.jpg', description: "You can overcome certain restrictions built in to your spells to prevent you from pushing your body past its safe limits. At any time, you {i}can{/i} {w}Boost{/w} any of your powers, but doing so will cause you to continually damage yourself. The more you boost at a time, the more pain and damage you suffer.", grade: 'kaarn' },
    { id: 'ace_in_the_hole', title: 'ACE IN THE HOLE', imageSrc: 'https://i.ibb.co/TMd7WbZr/b25.jpg', description: "{i}Requires {g}Metamagician.{/g}{/i} Nothing's funner than revealing a secret technique your foe didn't even know you had! Drawing from desperation, you can transform into a superpowered version of your alter ego which possesses a free {r}Xuth{/r}-tier spell of your choice. This form can be used 30 mins per month.", requires: ['metamagician'], grade: 'purth' },
];
