
import type { StarCrossedLoveSigil, StarCrossedLovePact } from '../../types';

// Star Crossed Love
export const STAR_CROSSED_LOVE_DATA = {
    title: "THE BLESSING OF STAR CROSSED LOVE",
    imageSrc: "https://i.ibb.co/d0jrxK9t/main4.jpg",
    description: `In her great magnanimity, the Mother does not mind Mages drawing power from sources other than herself. Plenty of other entities have obtained great power they can share with you, either {i}through{/i} {i}Theosis{/i}, drawing from the divinity of the Child of God like the Mother, or by taking advantage of distortions in the framework of our universe, or other even more esoteric means. However, while the Mother {i}tries to be{/i} {i}laissez faire{/i} with her subjects — often to her detriment — other entities won't be so kind, and will make demands of you. Displease them, and they'll take back their powers.

In my opinion, if there's ever a new Doctrine, this blessing will be the first to go. It's driven too many mages to turn on their sisters or go on rampages. The Mother always learns towards freedom, but if you study the history carefully, you'll realize that pretty much every problem that exists in our universe came about because she was too lenient...`
};

export const STAR_CROSSED_LOVE_SIGIL_TREE_DATA: StarCrossedLoveSigil[] = [
    { id: 'sworn_fealty', title: 'SWORN FEALTY', description: "You've vowed your undying loyalty to a powerful entity.\n+1 Pact", imageSrc: 'https://i.ibb.co/SFbsP2R/juathas.png', prerequisites: [], benefits: { pacts: 1 } },
    { id: 'dual_loyalty', title: 'DUAL LOYALTY', description: "Usually entities don't appreciate sharing, but...\n+1 Pact", imageSrc: 'https://i.ibb.co/rfs5FtF3/xuth.png', prerequisites: ['sworn_fealty'], benefits: { pacts: 1 } },
];

export const STAR_CROSSED_LOVE_PACTS_DATA: StarCrossedLovePact[] = [
    { id: 'onis_blessing', title: "ONI'S BLESSING", imageSrc: 'https://i.ibb.co/4wHGP0W5/c1.jpg', description: "You've been marked as the host of an Oni since birth, and thus enlisted in their endless war against all other Yokai. They're most common in Jipangu, but even in other Dominions, they will track you down and attempt to sow as much destruction in your life as they can, going after loved ones and sabotaging your life. You must never miss an opportunity to end any Yokai you meet permanently. In return, you get permanent Boosts to {i}all{/i} Good Tidings spells, and your guardian oni can appear to aid you in combat once per year. Design them with {w}100 Beast Points{/w}.", grade: 'xuth' },
    { id: 'jade_emperors_challenge', title: "THE JADE EMPEROR'S CHALLENGE", imageSrc: 'https://i.ibb.co/chVk5k32/c2.jpg', description: "The most powerful man in the Sinjade Doctrine who craved death but could find no foe able to grant it to him, up until he dueled the Mother herself, who could only just barely defeat him. Even at 1/10 the power of his mortal self, his spirit is still overflowing with strength to spare. To please him, you must defeat a truly powerful foe at least once every couple dozen years; each foe must be significantly stronger than the previous one. Completing {w}1 Xuth Trial{/w} grants a refund of {w}half{/w} its cost. Completing {w}2 Xuth Trials{/w} grants the refund and unlocks the ability to purchase a {w}3rd Xuth Trial{/w} at full price.", grade: 'xuth' },
    { id: 'lost_kronacks_deal', title: "LOST KRONACK'S DEAL", imageSrc: 'https://i.ibb.co/5xK2QtBD/c3.jpg', description: "The elusive leader of the Ninth Dominion, only know as a creature who made his way to our universe from the Greater Net, and who was left behind when his brethren returned to their home and left him behind. He asks only that, once every year, you bring him the soul of a mage for him to feast him, strengthening him. In return, you will be granted preternatural immunity from the effects of one section of spells, such as the {i}Metathermics{/i} section or the {i}Mental Manipulation{/i} section. Over time, he'll demand souls more and more often.", grade: 'xuth' },
    { id: 'sun_forgers_boon', title: "SUN FORGER'S BOON", imageSrc: 'https://i.ibb.co/zTZVxmmj/c4.jpg', description: "Having lost all magic, this ancient emperor turned to his own inventions to feed and shelter his people during the Forsaken Age, and he's since become the patron saint of human ingenuity. Any sigil that you use to buy a spell that creates a weapon, companion, beast, or vehicle is now halved in price. Additionally, at any point on the {i}Reference Page{/i}, you can convert 1 {bpx}BP{/bpx} into {w}2 Vehicle, Weapon, Beast or Companion Points{/w} as many times as you want (although you can still never invest more than {w}100 points{/w} into any one creation).", grade: 'xuth' },
    { id: 'cheissiliths_bargain', title: "CHEISSILITH'S BARGAIN", imageSrc: 'https://i.ibb.co/JWSPqbjh/c5.png', description: "Cheissilt was the first of the dragons, and is known for being unusually fluffy among them. At the end of the Forsaken Age, she is the very beast that the Mother rode into the Garden of Eden, and witnessed the slaying of God. Still acting as the Mother's right hand, she considers herself humanity's undying shepherd. She's convinced they'd survive longer if they abandoned specialization for variety. {j}Juathas{/j} sigils, including this one's, become completely free; however, the price of {g}Purth{/g} and {r}Xuth{/r} sigils is doubled.", grade: 'xuth' },
    { id: 'evoghos_vow', title: "EV'OGHOS' VOW", imageSrc: 'https://i.ibb.co/ccrTKtgN/c6.jpg', description: "The great and terrible \"god of the sea\", living in the stygian depths of the deepest trench of the Unterseeisch, many, many miles under the ocean's surface, a place so impossibly deep the laws of physics begin to break down. He shuns material possessions, believing a mage must be preoccupied by the spiritual; thus, if visited, he will allow you to convert 50 {fpx}FP{/fpx} {i}into{/i} 50 {bpx}BP{/bpx}. You must also take a vow of loneliness. You cannot choose any {w}Classmates{/w} {i}or{/i} {w}Colleagues{/w}; the only friends you can ever have in this world are the ones you magically create.", grade: 'xuth' },
    { id: 'kuri_odans_charm', title: "KURI-ODAN'S CHARM", imageSrc: 'https://i.ibb.co/wNsbKjFZ/c7.jpg', description: "For gamblers, the Kuri-Odan, the most powerful of the Yokai, will offer you a part of his soul in the form of a small charm, entrusting you to keep this vital part of him safe from harm. You lose {w}50 BP{/w}, {i}but gain{/i} {kp}100 KP{/kp}, which can be spent exclusively on sigils. Powers bought {i}with{/i} {kp}KP{/kp} {i}will{/i} slowly activate over time, likely taking a few centuries before you come to full power. This means your potential is much greater, but you'll be vulnerable for a long time: if anyone can break your charm, you will lose {i}every{/i} {kp}KP{/kp} {i}power{/i} you haven't yet activated.", grade: 'xuth' },
    { id: 'sinthrus_contract', title: "SINTHRU'S CONTRACT", imageSrc: 'https://i.ibb.co/LhXMYMg7/c8.jpg', description: "Desecrate your soul by swearing eternal loyalty to the Sinthru, the vilest devils who aim to kill the Mother and free the Child for their own no-doubt selfish purposes. You will be sworn to their service, and once people inevitably find out about this, you will be cast out by all of society, declared an enemy of all mankind and hunted down with the full force of Mother's empire. As long as you continue serving them, though, {i}all{/i} {bp}Sinthru{/bp} sigils are free as long as you have the prerequisite sigils, and there's no longer any limit on how many you can take.", grade: 'sinthru' },
];
