
import type { WorldlyWisdomSigil, WorldlyWisdomPower } from '../../types';

export const WORLDLY_WISDOM_DATA = {
    title: "THE BLESSING OF WORLDLY WISDOM",
    imageSrc: "https://i.ibb.co/SXMHZJ5n/main7.png",
    description: `Once thought to just be a form of temporal magic limited to organic tissue. It was unknown what it was useful for besides age manipulation and making crops grow, up until the two Braningan Sisters, Eleanor and Genevieve. They found that by applying this Blessing in very specific ways, they could not only accelerate or reverse natural processes, they could {i}modify{/i} them. Eleanor, a simple girl, dabbled in only the most practical applications of this art, but Genevieve, ever the scientist, delved deeper, perfecting truly amazing techniques with the ambition of one day inventing perfect immortality and invincibility. It seems she took her research {bpx}too far{/bpx}, however, and abandoned it out of horror.
    
A side note: on undead creatures, this magic actually increases the rate at which they {i}rot{/i}, rather than heal. Therefore, it's possible to actually {i}deal{/i} damage to them in this way. It's very entertaining!`
};

export const WORLDLY_WISDOM_SIGIL_TREE_DATA: WorldlyWisdomSigil[] = [
    { id: 'arborealist', title: 'ARBOREALIST', description: 'Expect popularity with these skills.', imageSrc: 'https://i.ibb.co/SFbsP2R/juathas.png', prerequisites: [], type: 'Arborealist', benefits: { eleanors: 1 } },
    { id: 'sanctified_i', title: 'SANCTIFIED I', description: '', imageSrc: 'https://i.ibb.co/Dg6nz0R1/purth.png', prerequisites: ['arborealist'], type: 'Sanctified', benefits: { genevieves: 1 } },
    { id: 'healer_i', title: 'HEALER I', description: '', imageSrc: 'https://i.ibb.co/zTm8fcLb/kaarn.png', prerequisites: ['arborealist'], type: 'Healer', benefits: { eleanors: 1 } },
    { id: 'healer_ii', title: 'HEALER II', description: '', imageSrc: 'https://i.ibb.co/zTm8fcLb/kaarn.png', prerequisites: ['healer_i'], type: 'Healer', benefits: { eleanors: 1 } },
    { id: 'healer_iii', title: 'HEALER III', description: '', imageSrc: 'https://i.ibb.co/zTm8fcLb/kaarn.png', prerequisites: ['healer_i'], type: 'Healer', benefits: { eleanors: 1 } },
    { id: 'sanctified_ii', title: 'SANCTIFIED II', description: '', imageSrc: 'https://i.ibb.co/Dg6nz0R1/purth.png', prerequisites: ['healer_ii'], type: 'Sanctified', benefits: { genevieves: 1 } },
    { id: 'healer_iv', title: 'HEALER IV', description: '', imageSrc: 'https://i.ibb.co/zTm8fcLb/kaarn.png', prerequisites: ['healer_iii'], type: 'Healer', benefits: { eleanors: 1 } },
    { id: 'dark_art', title: 'DARK ART', description: "Unlocks: The Reinman's Curse", imageSrc: 'https://i.ibb.co/nq80Y3pk/sinthru.png', prerequisites: ['healer_iv'], type: 'Dark Art', benefits: { genevieves: 1 }, unlocks: "the_reinmans_curse" },
    { id: 'sanctified_iii', title: 'SANCTIFIED III', description: '', imageSrc: 'https://i.ibb.co/Dg6nz0R1/purth.png', prerequisites: ['healer_iv'], type: 'Sanctified', benefits: { genevieves: 1 } },
];

export const ELEANORS_TECHNIQUES_DATA: WorldlyWisdomPower[] = [
    { id: 'healing_bliss', title: 'HEALING BLISS', imageSrc: 'https://i.ibb.co/PzCsWSh2/e1.jpg', description: "Focusing your power upon yourself or a single ally up close will allow you to stabilize even the worst condition and completely heal them, though it will still take a long while if they were in incredibly severe condition. This is the fastest healing power, but requires your undivided attention for a time.", grade: 'kaarn' },
    { id: 'defensive_circle', title: 'DEFENSIVE CIRCLE', imageSrc: 'https://i.ibb.co/F4fpqwpb/e2.png', description: "Creates a runic circle of light upon the ground beneath you with a radius of about 10 meters. You and any of your allies who stay within this circle will find themselves energized, less affected by fear or pain, moderately more magically powerful and durable, and enjoying a modest healing effect.", grade: 'kaarn' },
    { id: 'rejuvenating_bolt', title: 'REJUVENATING BOLT', imageSrc: 'https://i.ibb.co/TBFsbXVF/e3.jpg', description: "When you need healing {i}now!{/i} You can fire a magical bolt that can travel with extreme accuracy over very long distances — but don't miss, or it will be wasted! When it hits, it will near instantly heal a significant portion of the target's damage. Alas, it will take a couple minutes to charge another bolt.", grade: 'kaarn' },
    { id: 'guardian_angels', title: 'GUARDIAN ANGELS', imageSrc: 'https://i.ibb.co/YFJRmLNC/e4.jpg', description: "You can manifest your desire to protect a friend in the form of a tiny angel that will float around their head, significantly boosting their luck and providing a moderate passive healing effect. You can create up to three of these angels at a time; however, they can be targeted and destroyed by enemies.", grade: 'kaarn' },
    { id: 'psychic_surgery', title: 'PSYCHIC SURGERY', imageSrc: 'https://i.ibb.co/ymT4fgLy/e5.png', description: "{i}Requires {w}Healing Bliss.{/w}{/i} Slower and less fun than {w}Healing Bliss{/w}, but much more thorough! Almost anything can be healed through magical surgeries, from genetic disabilities, to metamagical debuffs, to minor curses and hexes, or even sadness or bad luck! Certain upgrades to the body can even be made by the brave.", requires: ['healing_bliss'], grade: 'kaarn' },
    { id: 'chloromancy', title: 'CHLOROMANCY', imageSrc: 'https://i.ibb.co/MDy5DD1N/e6.jpg', description: "You have absolute control over nearby plants and can grow and mutate them rapidly. Transform grass into massive vines that constrict and strangle foes, flowers into poison sprayers, tree branches into jutting spikes, etc. Gain vibrational sense of any movement near a plant within a mile radius.", grade: 'kaarn' },
    { id: 'botanic_mistresses', title: 'BOTANIC MISTRESSES', imageSrc: 'https://i.ibb.co/nNHHMVLd/e7.jpg', description: "From arable earth, you can summon servile dryads dedicated to serving your whims. It requires a bit of a ritual, and they only last for a couple hours, before returning to the earth; however, you can choose three other of {w}Eleanor's Techniques{/w} for them to be proficient in. Vulnerable to fire.", specialRequirement: 'requires_3_eleanor', grade: 'kaarn' },
    { id: 'maneaters', title: 'MANEATERS', imageSrc: 'https://i.ibb.co/jkfLzZ0Z/e8.jpg', description: "Can create and plant seeds that will, within seconds, grow into towering carnivorous plant monsters, from venus fly traps to pitcher plants, attempting to snatch mages with tentacles lined with a weakening poison. Trapped mages will take constant damage until they manage to escape.", grade: 'kaarn' },
];

export const GENEVIEVES_TECHNIQUES_DATA: WorldlyWisdomPower[] = [
    { id: 'flashback', title: 'FLASHBACK', imageSrc: 'https://i.ibb.co/JwHQd2ff/e9.jpg', description: "When within a certain range from a foe, you can expel a constant flow of energy from your hand that absorbs magical energy. Not only is this slightly painful for them, but it reverses their natural healing, causing their wounds to bleed more and slowly grow more severe rather than staunch or shrink. Once a large amount of energy is stored, you will be able to use it all in a quick burst to revert a target's body back to the way it was within two hours in the past, which can effectively instantly heal all damage if used correctly.", grade: 'purth' },
    { id: 'sustaining_bond', title: 'SUSTAINING BOND', imageSrc: 'https://i.ibb.co/yBR6pG0g/e10.png', description: "This magic requires you to have another individual with whom you share a deep and dedicated friendship or bond, to such an extent that it transcends the material realm. When their life is truly endangered, you will be overcome by emotion and release a burst of magic energy; for the next few minutes, their healing effect will be strengthened to the point they instantly recover from all damage, rendering them functionally invincible for the duration. This energy burst will leave you utterly exhausted for days afterwards.", grade: 'purth' },
    { id: 'tree_of_life', title: 'TREE OF LIFE', imageSrc: 'https://i.ibb.co/JWBhyh11/e11.jpg', description: "Scarcely, perhaps every year or so, you'll be able to create seeds that cause the surrounding few acres to explode with flora from the Garden of Eden. Buildings in this area will be completely overgrown. Just like in the real Garden, the forces of good shall be gradually healed while inside, while the forces of evil shall be gradually burned (this might include you, so be careful!). Most importantly, once in your life, you can consult the Tree of Life in the center of a garden to bring a person of your choice back to life, as long as they died in the past hour or so.", grade: 'purth' },
    { id: 'the_reinmans_curse', title: "THE REINMAN'S CURSE", imageSrc: 'https://i.ibb.co/JRx8GcwZ/e12.png', description: "{i}Requires {bp}Dark Art.{/bp}{/i} Nothing can completely kill a mage in a single hit - except for this one simple, yet feared, technique. Enchanted runes serve as 'land mines', exploding whenever a creature comes into proximity and afflicting them with a curse that causes aging to occur at tens of thousands of times the regular rate. The victim must have the curse removed quickly by an experienced exorcist, or face a slow and horrible death as their faculties leave them and their aging body becomes immobilized. A few hours later, all that's left is a decrepit skeleton.", requires: ['dark_art'], grade: 'sinthru' },
];
